import EnvelopingIsomorphism.Deformation.Gauge.LaurentSchoutenCoordinates

/-! The actual Laurent Schouten elementary moves, expressed on the precise
twisted-complex MC carrier used by gauge reflection. All values are retained
definitionally; the action is generated by genuine elementary exponentials. -/

noncomputable section

namespace EnvelopingIsomorphism.Deformation.Gauge.LaurentSchouten

open EnvelopingIsomorphism.FormalSeries PowerSeriesModule

set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 8

variable {K : Type*} [Field K] [CharZero K] {d : ℕ}

local instance : CharZero (Scalars K) := scalarCharZero

variable (π : Bivector K d)
variable (hπ : (polynomialSchoutenDGLA K d).laurent.IsMaurerCartan π)

abbrev sourceComplex := ((polynomialSchoutenDGLA K d).laurent.twist π hπ).complex

def sourceQuadratic : (sourceComplex π hπ).X 1 →ₗ[Scalars K]
    (sourceComplex π hπ).X 1 →ₗ[Scalars K] (sourceComplex π hπ).X 2 :=
  (2 : Scalars K)⁻¹ • bivectorBracket

theorem sourceComplex_d_one : ((sourceComplex π hπ).d 1 2).hom = bivectorBracket π :=
  twisted_d_one π hπ

abbrev SourceMC := MCSeries ((sourceComplex π hπ).d 1 2).hom (sourceQuadratic π hπ)

theorem sourceCurvature_eq (b : Families K d) :
    quadraticCurvature ((sourceComplex π hπ).d 1 2).hom (sourceQuadratic π hπ) b =
      quadraticCurvature (bivectorBracket π) ((2 : Scalars K)⁻¹ • bivectorBracket) b := by
  change quadraticCurvature ((sourceComplex π hπ).d 1 2).hom
    ((2 : Scalars K)⁻¹ • bivectorBracket) b = _
  rw [sourceComplex_d_one]

/-- The native complex and the concrete source MC equations have identical values. -/
def sourceMCEquiv : SourceMC π hπ ≃ MC π where
  toFun b := ⟨b.val, b.property.1, (sourceCurvature_eq π hπ b.val).symm.trans b.property.2⟩
  invFun b := ⟨b.val, b.property.1, (sourceCurvature_eq π hπ b.val).trans b.property.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

@[simp] theorem sourceMCEquiv_val (b : SourceMC π hπ) : (sourceMCEquiv π hπ b).val = b.val := rfl

@[simp] theorem sourceMCEquiv_symm_val (b : MC π) : ((sourceMCEquiv π hπ).symm b).val = b.val := rfl

abbrev SourceGroup (K : Type*) [Field K] (d : ℕ) := FreeGroup (ElementaryLabel (Vector K d))

def sourceMove (γ : ElementaryLabel (Vector K d)) : Equiv.Perm (SourceMC π hπ) :=
  (sourceMCEquiv π hπ).trans ((mcMove π hπ γ).trans (sourceMCEquiv π hπ).symm)

@[simp] theorem sourceMove_val (γ : ElementaryLabel (Vector K d)) (b : SourceMC π hπ) :
    (sourceMove π hπ γ b).val = motion π γ.order γ.positive γ.direction b.val := rfl

@[reducible] def sourceMulAction : MulAction (SourceGroup K d) (SourceMC π hπ) :=
  generatedMulAction (sourceMove π hπ)

def sourceOperators : SourceGroup K d →* GaugeUnit (LaurentSeries (Module.End K (PolynomialFunctions K d))) :=
  FreeGroup.lift mcCoordinateUnit

def sourceElementary (N : ℕ) (hN : 0 < N) (X : (sourceComplex π hπ).X 0) : SourceGroup K d :=
  FreeGroup.of ⟨N, hN, X⟩

theorem sourceElementary_near (N : ℕ) (hN : 0 < N) (X : (sourceComplex π hπ).X 0) :
    NearIdentity N (sourceOperators (sourceElementary π hπ N hN X)).series := by
  change NearIdentity N (FreeGroup.lift mcCoordinateUnit (FreeGroup.of ⟨N, hN, X⟩)).series
  rw [FreeGroup.lift_apply_of]
  exact elementaryGauge_near N hN _

section Action

local instance : MulAction (SourceGroup K d) (SourceMC π hπ) := sourceMulAction π hπ

theorem sourceElementary_smul (N : ℕ) (hN : 0 < N) (X : (sourceComplex π hπ).X 0)
    (b : SourceMC π hπ) :
    sourceElementary π hπ N hN X • b = sourceMove π hπ ⟨N, hN, X⟩ b := by
  change FreeGroup.lift (sourceMove π hπ) (FreeGroup.of ⟨N, hN, X⟩) b = _
  rw [FreeGroup.lift_apply_of]

theorem sourceElementary_agree (N : ℕ) (hN : 0 < N) (X : (sourceComplex π hπ).X 0)
    (b : SourceMC π hπ) : AgreeBelow N (sourceElementary π hπ N hN X • b).val b.val := by
  rw [sourceElementary_smul, sourceMove_val]
  exact motion_agree π N hN X b.val

theorem sourceElementary_leading (N : ℕ) (hN : 0 < N) (X : (sourceComplex π hπ).X 0)
    (b : SourceMC π hπ) :
    coeffV N (sourceElementary π hπ N hN X • b).val - coeffV N b.val =
      -(sourceComplex π hπ).d 0 1 X := by
  rw [sourceElementary_smul, sourceMove_val]
  exact motion_leading_twist π hπ N hN X b.val b.property.1

theorem sourceMCEquiv_smul (s : SourceGroup K d) (b : SourceMC π hπ) :
    sourceMCEquiv π hπ (s • b) = FreeGroup.lift (mcMove π hπ) s (sourceMCEquiv π hπ b) := by
  apply generated_equivariance (sourceMove π hπ) (mcMove π hπ) (sourceMCEquiv π hπ)
  intro γ x
  change sourceMCEquiv π hπ ((sourceMCEquiv π hπ).symm (mcMove π hπ γ (sourceMCEquiv π hπ x))) = _
  rw [Equiv.apply_symm_apply]
  rfl

/-- The represented source product is the actual affine bivector family. -/
def sourceBinary (b : SourceMC π hπ) :
    Binary (PowerSeries (Scalars K)) (PowerSeriesModule (Scalars K) (Functions K d)) :=
  extendBinary (single 0 (evaluateBivector π) + PowerSeriesModule.map evaluateBivector b.val)

theorem sourceBinary_eq_mcBinary (b : SourceMC π hπ) :
    sourceBinary π hπ b = mcBinary π (sourceMCEquiv π hπ b) := by
  let v : Families K d := b.val
  change extendBinary (single 0 (evaluateBivector π) + PowerSeriesModule.map evaluateBivector v) =
    extendBinary (rawSeries (single 0 π + v))
  rw [rawSeries_full]
  rfl

/-- Every source group word has the exact operator intertwining needed by the limit theorem. -/
theorem source_intertwines (s : SourceGroup K d) (b : SourceMC π hπ)
    (p q : PowerSeriesModule (Scalars K) (Functions K d)) :
    operator (PowerSeries.map LaurentOperator.actionHom (sourceOperators s).series)
        (sourceBinary π hπ b p q) =
      sourceBinary π hπ (s • b)
        (operator (PowerSeries.map LaurentOperator.actionHom (sourceOperators s).series) p)
        (operator (PowerSeries.map LaurentOperator.actionHom (sourceOperators s).series) q) := by
  rw [sourceBinary_eq_mcBinary, sourceBinary_eq_mcBinary, sourceMCEquiv_smul]
  exact mcGenerated_intertwines π hπ s (sourceMCEquiv π hπ b) p q

end Action

end EnvelopingIsomorphism.Deformation.Gauge.LaurentSchouten
