import EnvelopingIsomorphism.Lie.Nilradical
import EnvelopingIsomorphism.LinearAlgebra.TraceNilpotent
import Mathlib.Algebra.Lie.Engel
import Mathlib.LinearAlgebra.Trace
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-!
# Trace tests for the ordinary nilradical

The associative algebra generated by the adjoint operators preserves every Lie
ideal. If `x` belongs to a nilpotent ideal, multiplying `ad x` by any operator
in that associative algebra still gives a nilpotent operator.
-/

namespace EnvelopingIsomorphism.Lie

attribute [local instance 100] LieRing.ofAssociativeRing

variable (R L : Type*) [CommRing R] [LieRing L] [LieAlgebra R L]

/-- The associative subalgebra generated by the adjoint representation. -/
def adjointEnvelope : Subalgebra R (Module.End R L) :=
  Algebra.adjoin R (Set.range (LieAlgebra.ad R L))

variable {R L}

theorem ad_mem_adjointEnvelope (x : L) : LieAlgebra.ad R L x ∈ adjointEnvelope R L :=
  Algebra.subset_adjoin ⟨x, rfl⟩

/-- Every operator in the adjoint envelope preserves every Lie ideal. -/
theorem adjointEnvelope_preserves (I : LieIdeal R L) {T : Module.End R L}
    (hT : T ∈ adjointEnvelope R L) {x : L} (hx : x ∈ I) : T x ∈ I := by
  induction hT using Algebra.adjoin_induction generalizing x with
  | mem T hT =>
    obtain ⟨y, rfl⟩ := hT
    exact I.lie_mem hx
  | algebraMap r => simpa using I.smul_mem r hx
  | add T S hT hS hTi hSi => exact I.add_mem (hTi hx) (hSi hx)
  | mul T S hT hS hTi hSi => exact hTi (hSi hx)

/-- A nilpotent ideal element followed by an envelope operator is nilpotent. -/
theorem isNilpotent_ad_mul_of_mem_ideal (I : LieIdeal R L) [LieRing.IsNilpotent I]
    {x : L} (hx : x ∈ I) {T : Module.End R L} (hT : T ∈ adjointEnvelope R L) :
    IsNilpotent (LieAlgebra.ad R L x * T) := by
  obtain ⟨n, hn⟩ := (isNilpotent_ideal_iff_lcs_eq_bot I).mp inferInstance
  have hbound (m : ℕ) (y : L) :
      ((LieAlgebra.ad R L x * T) ^ m) y ∈ I.lcs L m := by
    induction m with
    | zero => simp
    | succ m ih =>
      rw [pow_succ', Module.End.mul_apply, Module.End.mul_apply, LieIdeal.lcs_succ]
      exact LieSubmodule.lie_mem_lie hx (adjointEnvelope_preserves (I.lcs L m) hT ih)
  refine ⟨n, ?_⟩
  ext y
  have h := hbound n y
  rw [hn] at h
  exact h

variable (R L)

/-- The Lie ideal annihilating the adjoint envelope under the trace pairing. -/
def adjointTraceIdeal : LieIdeal R L where
  carrier := { x | ∀ T ∈ adjointEnvelope R L,
    LinearMap.trace R L (LieAlgebra.ad R L x * T) = 0 }
  zero_mem' := by simp
  add_mem' hx hy := by
    intro T hT
    simp only [map_add, add_mul, hx T hT, hy T hT, zero_add]
  smul_mem' r x hx := by
    intro T hT
    simp only [map_smul, smul_mul_assoc, hx T hT, smul_zero]
  lie_mem {a x} hx := by
    intro T hT
    have hcomm : ⁅LieAlgebra.ad R L a, T⁆ ∈ adjointEnvelope R L := by
      rw [Ring.lie_def]
      exact (adjointEnvelope R L).sub_mem
        ((adjointEnvelope R L).mul_mem (ad_mem_adjointEnvelope a) hT)
        ((adjointEnvelope R L).mul_mem hT (ad_mem_adjointEnvelope a))
    rw [← lie_skew a x, map_neg, neg_mul, map_neg, LieHom.map_lie,
      LinearMap.trace_lie_mul_eq, hx _ hcomm, neg_zero]

variable {R L}

@[simp]
theorem mem_adjointTraceIdeal (x : L) :
    x ∈ adjointTraceIdeal R L ↔ ∀ T ∈ adjointEnvelope R L,
      LinearMap.trace R L (LieAlgebra.ad R L x * T) = 0 := Iff.rfl

/-- Every nilpotent Lie ideal satisfies all the trace tests. -/
theorem le_adjointTraceIdeal_of_isNilpotent [IsReduced R]
    (I : LieIdeal R L) [LieRing.IsNilpotent I] : I ≤ adjointTraceIdeal R L := by
  intro x hx T hT
  exact (LinearMap.isNilpotent_trace_of_isNilpotent
    (isNilpotent_ad_mul_of_mem_ideal I hx hT)).eq_zero

/-- The ordinary nilradical satisfies all the trace tests. -/
theorem nilradical_le_adjointTraceIdeal [IsReduced R] :
    nilradical R L ≤ adjointTraceIdeal R L := by
  apply sSup_le
  intro I hI
  haveI : LieRing.IsNilpotent I := hI
  exact le_adjointTraceIdeal_of_isNilpotent I

variable (R L)

/-- Trace tests on a basis of the adjoint envelope, collected into one linear map. -/
noncomputable def adjointTraceTests {ι : Type*} (b : Module.Basis ι R (adjointEnvelope R L)) :
    L →ₗ[R] (ι → R) where
  toFun x i := LinearMap.trace R L (LieAlgebra.ad R L x * (b i : Module.End R L))
  map_add' x y := by ext i; simp [add_mul]
  map_smul' r x := by ext i; simp

variable {R L}

/-- Testing a basis of the envelope gives precisely its trace-annihilator ideal. -/
theorem ker_adjointTraceTests {ι : Type*} (b : Module.Basis ι R (adjointEnvelope R L)) :
    LinearMap.ker (adjointTraceTests R L b) = (adjointTraceIdeal R L).toSubmodule := by
  ext x
  constructor
  · intro hx T hT
    let f : adjointEnvelope R L →ₗ[R] R :=
      { toFun S := LinearMap.trace R L (LieAlgebra.ad R L x * (S : Module.End R L))
        map_add' S U := by simp [mul_add]
        map_smul' r S := by simp }
    have hf : f = 0 := b.ext fun i => by
      exact congrFun (LinearMap.mem_ker.mp hx) i
    exact LinearMap.congr_fun hf ⟨T, hT⟩
  · intro hx
    apply LinearMap.mem_ker.mpr
    funext i
    exact hx _ (b i).property

section Field

variable {k V : Type*} [Field k] [CharZero k] [LieRing V] [LieAlgebra k V]
  [Module.Finite k V]

/-- In characteristic zero, the trace-annihilator ideal is intrinsically nilpotent. -/
instance adjointTraceIdealIsNilpotent : LieRing.IsNilpotent (adjointTraceIdeal k V) := by
  have hnil (x : adjointTraceIdeal k V) : IsNilpotent (LieAlgebra.ad k V (x : V)) := by
    apply EnvelopingIsomorphism.LinearAlgebra.isNilpotent_of_trace_pow_eq_zero
    intro n hn
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
    rw [pow_succ']
    exact x.property _ ((adjointEnvelope k V).pow_mem (ad_mem_adjointEnvelope (x : V)) m)
  haveI : LieModule.IsNilpotent (adjointTraceIdeal k V) V :=
    (LieModule.isNilpotent_iff_forall' (R := k)).mpr hnil
  exact isNilpotent_of_ideal_action (adjointTraceIdeal k V)

/-- The ordinary nilradical is the trace annihilator of the adjoint envelope. -/
theorem nilradical_eq_adjointTraceIdeal : nilradical k V = adjointTraceIdeal k V :=
  le_antisymm nilradical_le_adjointTraceIdeal (le_nilradical (adjointTraceIdeal k V))

/-- A finite family of linear trace tests defines the ordinary nilradical. -/
theorem ker_adjointTraceTests_eq_nilradical {ι : Type*}
    (b : Module.Basis ι k (adjointEnvelope k V)) :
    LinearMap.ker (adjointTraceTests k V b) = (nilradical k V).toSubmodule := by
  rw [ker_adjointTraceTests, nilradical_eq_adjointTraceIdeal]

end Field

end EnvelopingIsomorphism.Lie
