import EnvelopingIsomorphism.Enveloping.AdicFiltration
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Tactic.Abel

/-! First-order approximation of an algebra generated by a linear subspace.
No commutativity of the ambient algebra or of the generating subspace is
needed. The square of the containing two-sided ideal absorbs all nonlinear
terms. -/

namespace EnvelopingIsomorphism.Identification

variable {R A : Type*} [CommRing R] [Ring A] [Algebra R A]

theorem adjoin_le_firstOrder (X : Submodule R A) (I : TwoSidedIdeal A)
    (hX : X ≤ I.asIdeal.restrictScalars R) :
    (Algebra.adjoin R (X : Set A)).toSubmodule ≤
      1 ⊔ (X ⊔ Enveloping.adicPower R A I 2) := by
  let V : Submodule R A := I.asIdeal.restrictScalars R
  let J : Submodule R A := Enveloping.adicPower R A I 2
  let Z : Submodule R A := X ⊔ J
  let S : Submodule R A := 1 ⊔ Z
  have hJV : J ≤ V := by
    intro x hx
    exact Ideal.pow_le_self (show (2 : ℕ) ≠ 0 by decide) hx
  have hZV : Z ≤ V := sup_le hX hJV
  have hZZ : Z * Z ≤ J := by
    calc
      Z * Z ≤ V * V := mul_le_mul' hZV hZV
      _ = J := by
        simpa only [pow_two] using
          (Enveloping.adicPower_positive R A I (show (2 : ℕ) ≠ 0 by decide)).symm
  have hSS : S * S ≤ S := by
    change (1 ⊔ Z) * (1 ⊔ Z) ≤ 1 ⊔ Z
    rw [Submodule.sup_mul 1 Z (1 ⊔ Z), Submodule.mul_sup 1 1 Z,
      Submodule.mul_sup Z 1 Z]
    simp only [one_mul, mul_one]
    exact sup_le (sup_le le_sup_left le_sup_right)
      (sup_le le_sup_right (hZZ.trans (le_sup_right.trans le_sup_right)))
  have h1 : (1 : A) ∈ S := Submodule.one_le.mp le_sup_left
  let T : Subalgebra R A :=
    S.toSubalgebra h1 (fun x y hx hy => hSS (Submodule.mul_mem_mul hx hy))
  have hXT : (X : Set A) ⊆ T := by
    intro x hx
    change x ∈ S
    have hXS : X ≤ S :=
      (show X ≤ Z from le_sup_left).trans (show Z ≤ S from le_sup_right)
    exact hXS hx
  have hadj : Algebra.adjoin R (X : Set A) ≤ T := Algebra.adjoin_le_iff.mpr hXT
  exact fun x hx => hadj hx

/-- An augmentation removes the scalar term of this first-order
approximation. This is the only Taylor information needed for C2. -/
theorem exists_firstOrder_of_adjoin (X : Submodule R A) (I : TwoSidedIdeal A)
    (hX : X ≤ I.asIdeal.restrictScalars R) (ε : A →ₐ[R] R)
    (hε : ∀ a ∈ I.asIdeal, ε a = 0)
    {p : A} (hp : p ∈ Algebra.adjoin R (X : Set A)) :
    ∃ x ∈ X, p - algebraMap R A (ε p) - x ∈ Enveloping.adicPower R A I 2 := by
  have hs := adjoin_le_firstOrder X I hX hp
  obtain ⟨rA, hrA, z, hz, hsum⟩ := Submodule.mem_sup.mp hs
  obtain ⟨r, hr⟩ := Submodule.mem_one.mp hrA
  obtain ⟨x, hx, j, hj, hz⟩ := Submodule.mem_sup.mp hz
  have hjI : j ∈ I.asIdeal :=
    Ideal.pow_le_self (show (2 : ℕ) ≠ 0 by decide) hj
  have hep : ε p = r := by
    rw [← hsum, ← hr, ← hz, map_add, map_add, AlgHom.commutes,
      hε x (hX hx), hε j hjI, add_zero, add_zero]
    simp
  refine ⟨x, hx, ?_⟩
  have heq : p - algebraMap R A (ε p) - x = j := by
    rw [hep, ← hsum, ← hr, ← hz]
    abel
  rwa [heq]

end EnvelopingIsomorphism.Identification
