import EnvelopingIsomorphism.PBW.Weighted
import EnvelopingIsomorphism.Enveloping.AdicFiltration
import EnvelopingIsomorphism.Enveloping.Quotient
import EnvelopingIsomorphism.Lie.Nilradical
import EnvelopingIsomorphism.Lie.NilpotentIdealAction
import EnvelopingIsomorphism.LinearAlgebra.AdaptedBasis

/-! The weighted PBW filtration associated to the lower central series of an ideal. -/

noncomputable section

namespace EnvelopingIsomorphism.Identification

open UniversalEnvelopingAlgebra
open EnvelopingIsomorphism Enveloping Lie PBW

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The two-sided ideal generated by a Lie ideal in its native enveloping algebra. -/
abbrev envelopingIdeal (N : LieIdeal R L) : TwoSidedIdeal (UniversalEnvelopingAlgebra R L) :=
  Enveloping.lieIdealGenerated N

theorem ι_mem_envelopingIdeal {N : LieIdeal R L} {x : L} (hx : x ∈ N) :
    ι R x ∈ envelopingIdeal N :=
  TwoSidedIdeal.subset_span ⟨x, hx, rfl⟩

theorem adicPower_antitone {A : Type*} [Ring A] [Algebra R A]
    (I : TwoSidedIdeal A) {m n : ℕ} (h : m ≤ n) :
    adicPower R A I n ≤ adicPower R A I m := by
  intro x hx
  exact Ideal.pow_le_pow_right h hx

theorem lie_mem_adicPower {A : Type*} [Ring A] [Algebra R A]
    (I : TwoSidedIdeal A) {m n : ℕ} {x y : A}
    (hx : x ∈ adicPower R A I m) (hy : y ∈ adicPower R A I n) :
    ⁅x, y⁆ ∈ adicPower R A I (m + n) := by
  rw [LieRing.of_associative_ring_bracket]
  apply Submodule.sub_mem
  · rw [adicPower_mul]
    exact Submodule.mul_mem_mul hx hy
  · rw [Nat.add_comm, adicPower_mul]
    exact Submodule.mul_mem_mul hy hx

theorem ι_mem_adicPower_one {N : LieIdeal R L} {x : L} (hx : x ∈ N) :
    ι R x ∈ adicPower R _ (envelopingIdeal N) 1 := by
  change ι R x ∈ (envelopingIdeal N).asIdeal ^ 1
  simpa only [Submodule.pow_one, TwoSidedIdeal.mem_asIdeal] using ι_mem_envelopingIdeal hx

/-- The usual `γ_(n+1) N` lies in the `(n+1)`st power of its enveloping ideal. -/
theorem lowerCentralSeries_le_comap_adicPower (N : LieIdeal R L) (n : ℕ) :
    (lowerCentralSeriesOfIdeal N n).toSubmodule ≤
      (adicPower R _ (envelopingIdeal N) (n + 1)).comap (ι R).toLinearMap := by
  induction n with
  | zero => exact fun x hx ↦ ι_mem_adicPower_one hx
  | succ n ih =>
    rw [lowerCentralSeriesOfIdeal_succ, LieSubmodule.lieIdeal_oper_eq_linear_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨x, y, rfl⟩
    change ι R ⁅(x : L), (y : L)⁆ ∈
      adicPower R (UniversalEnvelopingAlgebra R L) (envelopingIdeal N) (n + 1 + 1)
    rw [(ι R).map_lie]
    have h := lie_mem_adicPower (envelopingIdeal N)
      (ι_mem_adicPower_one x.property) (ih y.property)
    simpa only [Nat.add_comm 1 (n + 1), LieHom.coe_toLinearMap] using h

/-- Brackets add the usual lower-central degrees. -/
theorem lowerCentralSeries_lie_le (N : LieIdeal R L) (i j : ℕ) :
    ⁅lowerCentralSeriesOfIdeal N i, lowerCentralSeriesOfIdeal N j⁆ ≤
      lowerCentralSeriesOfIdeal N (i + j + 1) := by
  induction i generalizing j with
  | zero => simp
  | succ i ih =>
    apply (LieSubmodule.lie_le_iff _ _ _).mpr
    intro x hx y hy
    have hx' : x ∈ Submodule.span R
        { ⁅(a : L), (z : L)⁆ | (a : N) (z : lowerCentralSeriesOfIdeal N i) } := by
      simpa only [lowerCentralSeriesOfIdeal_succ,
        ← LieSubmodule.mem_toSubmodule, LieSubmodule.lieIdeal_oper_eq_linear_span] using hx
    change ⁅x, y⁆ ∈ (lowerCentralSeriesOfIdeal N (i + 1 + j + 1)).toSubmodule
    clear hx
    induction hx' using Submodule.span_induction with
    | mem z hz =>
      obtain ⟨a, z, rfl⟩ := hz
      rw [lie_lie]
      apply Submodule.sub_mem (lowerCentralSeriesOfIdeal N (i + 1 + j + 1)).toSubmodule
      · have hz := (ih j) (LieSubmodule.lie_mem_lie z.property hy)
        have h := LieSubmodule.lie_mem_lie a.property hz
        simpa only [LieSubmodule.mem_toSubmodule, ← lowerCentralSeriesOfIdeal_succ, Nat.add_assoc,
          Nat.add_left_comm, Nat.add_comm] using h
      · have hay : ⁅(a : L), y⁆ ∈ lowerCentralSeriesOfIdeal N (j + 1) :=
          by simpa only [lowerCentralSeriesOfIdeal_succ] using LieSubmodule.lie_mem_lie a.property hy
        have h := (ih (j + 1)) (LieSubmodule.lie_mem_lie z.property hay)
        simpa only [LieSubmodule.mem_toSubmodule, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using h
    | zero => simp
    | add x z _ _ hx hz => simpa only [add_lie] using Submodule.add_mem _ hx hz
    | smul a x _ hx => simpa only [smul_lie] using Submodule.smul_mem _ a hx

/-- The filtration has ambient degree zero and usual lower-central degree `d≥1`. -/
def lowerCentralFiltration (N : LieIdeal R L) : ℕ → LieIdeal R L
  | 0 => ⊤
  | n + 1 => lowerCentralSeriesOfIdeal N n

@[simp] theorem lowerCentralFiltration_zero (N : LieIdeal R L) :
    lowerCentralFiltration N 0 = ⊤ := rfl

@[simp] theorem lowerCentralFiltration_succ (N : LieIdeal R L) (n : ℕ) :
    lowerCentralFiltration N (n + 1) = lowerCentralSeriesOfIdeal N n := rfl

theorem lowerCentralFiltration_lie_le (N : LieIdeal R L) (d e : ℕ) :
    ⁅lowerCentralFiltration N d, lowerCentralFiltration N e⁆ ≤
      lowerCentralFiltration N (d + e) := by
  cases d with
  | zero => simpa only [lowerCentralFiltration_zero, zero_add] using
      LieSubmodule.lie_le_right (lowerCentralFiltration N e) (⊤ : LieIdeal R L)
  | succ d =>
    cases e with
    | zero => simpa only [lowerCentralFiltration_zero, add_zero] using
        LieSubmodule.lie_le_left (lowerCentralFiltration N (d + 1)) (⊤ : LieIdeal R L)
    | succ e =>
      rw [show d + 1 + (e + 1) = (d + e + 1) + 1 by omega]
      exact lowerCentralSeries_lie_le N d e

variable {α : Type*} [LinearOrder α] (b : Module.Basis α R L) (ω : α → ℕ)

/-- A basis adapted to all layers of the lower-central filtration. Weights may vanish. -/
def IsLowerCentralAdapted (N : LieIdeal R L) : Prop :=
  ∀ d, Submodule.span R (b '' {i | d ≤ ω i}) = (lowerCentralFiltration N d).toSubmodule

theorem adapted_basis_mem (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N) (i : α) :
    b i ∈ lowerCentralFiltration N (ω i) := by
  change b i ∈ (lowerCentralFiltration N (ω i)).toSubmodule
  rw [← ha]
  exact Submodule.subset_span ⟨i, by simp, rfl⟩

theorem adapted_bracket_weight (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (i j a : α) (hc : b.repr ⁅b i, b j⁆ a ≠ 0) : ω i + ω j ≤ ω a := by
  have h := lowerCentralFiltration_lie_le N (ω i) (ω j)
    (LieSubmodule.lie_mem_lie (adapted_basis_mem b ω N ha i) (adapted_basis_mem b ω N ha j))
  change ⁅b i, b j⁆ ∈ (lowerCentralFiltration N (ω i + ω j)).toSubmodule at h
  rw [← ha] at h
  exact b.repr_support_subset_of_mem_span _ h (Finsupp.mem_support_iff.mpr hc)

/-- The first PBW coordinates of a linear Lie vector are exactly its original coordinates. -/
theorem pbwBasis_repr_ι (x : L) :
    (pbwBasis b).repr (ι R x) = (b.repr x).mapDomain (fun i ↦ Finsupp.single i (1 : ℕ)) := by
  have h : (pbwBasis b).repr.toLinearMap.comp (ι R).toLinearMap =
      (Finsupp.lmapDomain R R (fun i ↦ Finsupp.single i (1 : ℕ))).comp b.repr.toLinearMap := by
    apply b.ext
    intro i
    change (pbwBasis b).repr (ι R (b i)) =
      (b.repr (b i)).mapDomain (fun j ↦ Finsupp.single j (1 : ℕ))
    rw [← pbwBasis_single b i, (pbwBasis b).repr_self, b.repr_self]
    simp
  exact LinearMap.congr_fun h x

theorem ι_mem_weightedLower_iff (d : ℕ) (x : L) :
    ι R x ∈ weightedLower b ω d ↔ x ∈ Submodule.span R (b '' {i | d ≤ ω i}) := by
  classical
  rw [mem_weightedLower_iff, b.mem_span_image, pbwBasis_repr_ι]
  constructor
  · intro h i hi
    have hm : Finsupp.single i (1 : ℕ) ∈
        ((b.repr x).mapDomain (fun j ↦ Finsupp.single j (1 : ℕ))).support := by
      rw [Finsupp.mem_support_iff, Finsupp.mapDomain_apply (Finsupp.single_left_injective (by decide))]
      exact Finsupp.mem_support_iff.mp hi
    simpa only [Finsupp.weight_single, one_nsmul, Set.mem_setOf_eq] using h _ hm
  · intro h m hm
    obtain ⟨i, hi, rfl⟩ := Finset.mem_image.mp (Finsupp.mapDomain_support hm)
    simpa only [Finsupp.weight_single, one_nsmul, Set.mem_setOf_eq] using h hi

theorem adapted_ι_mem_adicPower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (i : α) : ι R (b i) ∈ adicPower R _ (envelopingIdeal N) (ω i) := by
  have hi := adapted_basis_mem b ω N ha i
  cases hω : ω i with
  | zero => rw [adicPower_zero]; exact Submodule.mem_top
  | succ n =>
    rw [hω] at hi
    exact lowerCentralSeries_le_comap_adicPower N n hi

/-- Products of adapted basis vectors belong to the power given by total weight. -/
theorem adapted_word_mem_adicPower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (w : List α) :
    (w.map (ι R ∘ b)).prod ∈ adicPower R _ (envelopingIdeal N) (wordWeight ω w) := by
  induction w with
  | nil => rw [wordWeight_nil, adicPower_zero]; exact Submodule.mem_top
  | cons i w ih =>
    simp only [List.map_cons, List.prod_cons, Function.comp_apply, wordWeight_cons]
    rw [adicPower_mul]
    exact Submodule.mul_mem_mul (adapted_ι_mem_adicPower b ω N ha i) ih

theorem weightedLower_le_adicPower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (d : ℕ) : weightedLower b ω d ≤ adicPower R _ (envelopingIdeal N) d := by
  apply Submodule.span_le.mpr
  rintro _ ⟨m, hm, rfl⟩
  have h := adapted_word_mem_adicPower b ω N ha (orderedWord m)
  rw [wordWeight, wordIndex_orderedWord, ← pbwBasis_apply] at h
  exact adicPower_antitone _ hm h

/-- The weighted degree-one submodule contains the two-sided ideal generated by `N`. -/
theorem adicPower_one_le_weightedLower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N) :
    adicPower R _ (envelopingIdeal N) 1 ≤ weightedLower b ω 1 := by
  intro x hx
  have hx' : x ∈ envelopingIdeal N := by
    change x ∈ (envelopingIdeal N).asIdeal ^ 1 at hx
    rw [Submodule.pow_one] at hx
    exact TwoSidedIdeal.mem_asIdeal.mp hx
  have hc := adapted_bracket_weight b ω N ha
  clear hx
  change x ∈ TwoSidedIdeal.span (ι R '' (N : Set L)) at hx'
  induction hx' using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨y, hy, rfl⟩ := hx
    rw [ι_mem_weightedLower_iff, ha]
    exact hy
  | zero => exact Submodule.zero_mem _
  | add x y hx hy hx' hy' => exact Submodule.add_mem _ hx' hy'
  | neg x hx hx' => exact Submodule.neg_mem _ hx'
  | left_absorb a x hx hx' =>
    have ha0 : a ∈ weightedLower b ω 0 := by rw [weightedLower_zero]; exact Submodule.mem_top
    exact weightedLower_mul_le b ω hc 0 1 (Submodule.mul_mem_mul ha0 hx')
  | right_absorb a x hx hx' =>
    have ha0 : a ∈ weightedLower b ω 0 := by rw [weightedLower_zero]; exact Submodule.mem_top
    exact weightedLower_mul_le b ω hc 1 0 (Submodule.mul_mem_mul hx' ha0)

theorem adicPower_le_weightedLower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (d : ℕ) : adicPower R _ (envelopingIdeal N) d ≤ weightedLower b ω d := by
  induction d with
  | zero => rw [weightedLower_zero]; exact le_top
  | succ d ih =>
    rw [adicPower_mul]
    apply Submodule.mul_le.mpr
    intro x hx y hy
    exact weightedLower_mul_le b ω (adapted_bracket_weight b ω N ha) d 1
      (Submodule.mul_mem_mul (ih hx) (adicPower_one_le_weightedLower b ω N ha hy))

/-- The actual adic filtration equals the PBW filtration of an adapted lower-central basis. -/
theorem adicPower_eq_weightedLower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N)
    (d : ℕ) : adicPower R _ (envelopingIdeal N) d = weightedLower b ω d :=
  le_antisymm (adicPower_le_weightedLower b ω N ha d) (weightedLower_le_adicPower b ω N ha d)

/-- Intersecting the actual enveloping-ideal powers with the Lie algebra recovers every layer. -/
theorem comap_ι_adicPower (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N) (d : ℕ) :
    (adicPower R _ (envelopingIdeal N) d).comap (ι R).toLinearMap =
      (lowerCentralFiltration N d).toSubmodule := by
  rw [adicPower_eq_weightedLower b ω N ha]
  ext x
  change ι R x ∈ weightedLower b ω d ↔ x ∈ (lowerCentralFiltration N d).toSubmodule
  rw [ι_mem_weightedLower_iff, ha]

theorem comap_ι_adicPower_succ (N : LieIdeal R L) (ha : IsLowerCentralAdapted b ω N) (n : ℕ) :
    (adicPower R _ (envelopingIdeal N) (n + 1)).comap (ι R).toLinearMap =
      (lowerCentralSeriesOfIdeal N n).toSubmodule :=
  comap_ι_adicPower b ω N ha (n + 1)

theorem lowerCentralFiltration_antitone (N : LieIdeal R L) : Antitone (lowerCentralFiltration N) := by
  apply antitone_nat_of_succ_le
  intro d
  cases d with
  | zero => exact le_top
  | succ d =>
    change lowerCentralSeriesOfIdeal N (d + 1) ≤ lowerCentralSeriesOfIdeal N d
    rw [lowerCentralSeriesOfIdeal_succ]
    exact LieSubmodule.lie_le_right (lowerCentralSeriesOfIdeal N d) N

theorem lowerCentralSeries_le_ideal_lcs (N : LieIdeal R L) (n : ℕ) :
    lowerCentralSeriesOfIdeal N n ≤ N.lcs L n := by
  induction n with
  | zero => exact le_top
  | succ n ih =>
    rw [lowerCentralSeriesOfIdeal_succ, LieIdeal.lcs_succ]
    exact LieSubmodule.mono_lie_right N ih

theorem exists_lowerCentralFiltration_eq_bot (N : LieIdeal R L) [LieRing.IsNilpotent N] :
    ∃ c : ℕ, lowerCentralFiltration N (c + 1) = ⊥ := by
  obtain ⟨c, hc⟩ := (isNilpotent_ideal_iff_lcs_eq_bot N).mp inferInstance
  exact ⟨c, le_bot_iff.mp ((lowerCentralSeries_le_ideal_lcs N c).trans_eq hc)⟩

section Field

variable {k M : Type*} [Field k] [LieRing M] [LieAlgebra k M] [Module.Finite k M]

/-- Nilpotent ideals in finite-dimensional Lie algebras have actual adapted weighted bases. -/
theorem exists_lowerCentral_adapted (N : LieIdeal k M) [LieRing.IsNilpotent N] :
    ∃ n : ℕ, ∃ b : Module.Basis (Fin n) k M, ∃ ω : Fin n → ℕ,
      IsLowerCentralAdapted b ω N := by
  obtain ⟨c, hc⟩ := exists_lowerCentralFiltration_eq_bot N
  have hzero : (lowerCentralFiltration N 0).toSubmodule = ⊤ := rfl
  have hmono : Antitone (fun d ↦ (lowerCentralFiltration N d).toSubmodule) :=
    fun i j hij ↦ lowerCentralFiltration_antitone N hij
  have hterm : (lowerCentralFiltration N (c + 1)).toSubmodule = ⊥ := by rw [hc]; rfl
  obtain ⟨n, b, ω, _, hω⟩ := LinearAlgebra.exists_adapted_weighted_basis
    (fun d ↦ (lowerCentralFiltration N d).toSubmodule) hzero hmono c hterm
  exact ⟨n, b, ω, hω⟩

/-- For nilpotent ideals, the enveloping ideal powers recover the lower central series. -/
theorem comap_ι_adicPower_succ_of_nilpotent (N : LieIdeal k M) [LieRing.IsNilpotent N] (n : ℕ) :
    (adicPower k _ (envelopingIdeal N) (n + 1)).comap (ι k).toLinearMap =
      (lowerCentralSeriesOfIdeal N n).toSubmodule := by
  obtain ⟨d, b, ω, ha⟩ := exists_lowerCentral_adapted N
  exact comap_ι_adicPower_succ b ω N ha n

/-- Actual adapted PBW coordinates describe all powers of the generated ideal simultaneously. -/
theorem exists_adicPower_eq_weightedLower (N : LieIdeal k M) [LieRing.IsNilpotent N] :
    ∃ n : ℕ, ∃ b : Module.Basis (Fin n) k M, ∃ ω : Fin n → ℕ,
      IsLowerCentralAdapted b ω N ∧
        ∀ d, adicPower k _ (envelopingIdeal N) d = weightedLower b ω d := by
  obtain ⟨n, b, ω, ha⟩ := exists_lowerCentral_adapted N
  exact ⟨n, b, ω, ha, adicPower_eq_weightedLower b ω N ha⟩

end Field

end EnvelopingIsomorphism.Identification
