import EnvelopingIsomorphism.Identification.LeadingTerms
import EnvelopingIsomorphism.Identification.AdjoinFirstOrder
import EnvelopingIsomorphism.Identification.MetabelianNilradicalData
import EnvelopingIsomorphism.Identification.MetabelianScalarExtension
import EnvelopingIsomorphism.Identification.IntrinsicIdeal
import EnvelopingIsomorphism.Identification.Solvability
import EnvelopingIsomorphism.Enveloping.Augmentation

/-!
# Initial linear approximations of an augmentation-preserving UEA isomorphism

The metabelian LN/LF descriptions give polynomial representatives after
quotienting by `[N,N]`. Lift those polynomials, use that the quotient kernel is
in the square of the enveloping ideal, and remove the scalar by augmentation.
-/

noncomputable section

namespace EnvelopingIsomorphism.Identification

open UniversalEnvelopingAlgebra
open EnvelopingIsomorphism Enveloping Lie

attribute [local instance 100] LieRing.ofAssociativeRing

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

@[simp]
theorem derivedQuotientMap_ι (N : LieIdeal R L) (x : L) :
    Enveloping.quotientMap ⁅N, N⁆ (ι R x) = ι R (quotientLieHom ⁅N, N⁆ x) :=
  Enveloping.quotientMap_ι ⁅N, N⁆ x

/-- Polynomial elements of the actual ideal image lift to polynomials in the original ideal. -/
theorem exists_polynomial_lift_derivedQuotient (N : LieIdeal R L)
    {p : UniversalEnvelopingAlgebra R (idealDerivedQuotient N)}
    (hp : p ∈ idealPolynomialPart (idealAbelianImage N)) :
    ∃ q ∈ idealPolynomialPart N, Enveloping.quotientMap ⁅N, N⁆ q = p := by
  induction hp using Algebra.adjoin_induction with
  | mem p hp =>
    obtain ⟨h, rfl⟩ := hp
    obtain ⟨x, hx⟩ := LieIdeal.mem_map_of_surjective (quotientLieHom_surjective ⁅N, N⁆) h.property
    refine ⟨ι R (x : L), ι_mem_idealPolynomialPart N x.property, ?_⟩
    rw [derivedQuotientMap_ι, hx]
  | algebraMap r =>
    exact ⟨algebraMap R _ r, Subalgebra.algebraMap_mem _ r, AlgHom.commutes _ r⟩
  | add p q hp hq hp' hq' =>
    obtain ⟨a, ha, rfl⟩ := hp'
    obtain ⟨b, hb, rfl⟩ := hq'
    exact ⟨a + b, add_mem ha hb, map_add _ a b⟩
  | mul p q hp hq hp' hq' =>
    obtain ⟨a, ha, rfl⟩ := hp'
    obtain ⟨b, hb, rfl⟩ := hq'
    exact ⟨a * b, mul_mem ha hb, map_mul _ a b⟩

/-- The ideal generated by the commutators of N is contained in the square of the ideal generated by N. -/
theorem mem_adicSquare_of_mem_derivedIdeal (N : LieIdeal R L)
    {a : UniversalEnvelopingAlgebra R L} (ha : a ∈ envelopingIdeal ⁅N, N⁆) :
    a ∈ adicPower R _ (envelopingIdeal N) 2 := by
  have h : envelopingIdeal ⁅N, N⁆ ≤ ((envelopingIdeal N).asIdeal ^ 2).toTwoSided := by
    apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨x, hx, rfl⟩
    change ι R x ∈ ((envelopingIdeal N).asIdeal ^ 2).toTwoSided
    rw [Ideal.mem_toTwoSided]
    exact lowerCentralSeries_le_comap_adicPower N 1 hx
  change a ∈ (envelopingIdeal N).asIdeal ^ 2
  simpa only [Ideal.mem_toTwoSided] using h ha

/-- The canonical augmentation vanishes on every enveloping ideal generated by Lie vectors. -/
theorem augmentation_eq_zero_of_mem_envelopingIdeal (N : LieIdeal R L)
    {a : UniversalEnvelopingAlgebra R L} (ha : a ∈ envelopingIdeal N) :
    augmentation R L a = 0 := by
  have h : envelopingIdeal N ≤ TwoSidedIdeal.ker (augmentation R L) := by
    apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨x, hx, rfl⟩
    change ι R x ∈ TwoSidedIdeal.ker (augmentation R L)
    rw [TwoSidedIdeal.mem_ker, augmentation_ι]
  exact (TwoSidedIdeal.mem_ker _).mp (h ha)

/-- A polynomial in N has its augmentation and a linear N-term as its complete first-order part. -/
theorem exists_polynomial_firstOrder (N : LieIdeal R L)
    {p : UniversalEnvelopingAlgebra R L} (hp : p ∈ idealPolynomialPart N) :
    ∃ x ∈ N, p - algebraMap R _ (augmentation R L p) - ι R x ∈
      adicPower R _ (envelopingIdeal N) 2 := by
  let X := ((ι R).toLinearMap.comp N.toSubmodule.subtype).range
  have hX : X ≤ (envelopingIdeal N).asIdeal.restrictScalars R := by
    rintro _ ⟨x, rfl⟩
    exact ι_mem_envelopingIdeal x.property
  have hp' : p ∈ Algebra.adjoin R (X : Set (UniversalEnvelopingAlgebra R L)) := hp
  obtain ⟨x, hx, he⟩ := exists_firstOrder_of_adjoin X (envelopingIdeal N) hX
    (augmentation R L) (fun a ha => augmentation_eq_zero_of_mem_envelopingIdeal N ha) hp'
  obtain ⟨y, rfl⟩ := hx
  exact ⟨y, y.property, he⟩

/-- A polynomial representative after the derived quotient gives a first-order N-representative before quotienting. -/
theorem exists_firstOrder_of_quotient_polynomial (N : LieIdeal R L)
    {a : UniversalEnvelopingAlgebra R L}
    (ha : Enveloping.quotientMap ⁅N, N⁆ a ∈ idealPolynomialPart (idealAbelianImage N)) :
    ∃ x ∈ N, a - algebraMap R _ (augmentation R L a) - ι R x ∈
      adicPower R _ (envelopingIdeal N) 2 := by
  obtain ⟨p, hp, hpa⟩ := exists_polynomial_lift_derivedQuotient N ha
  have hker : a - p ∈ envelopingIdeal ⁅N, N⁆ := by
    apply (Enveloping.quotientMap_eq_zero_iff ⁅N, N⁆ (a - p)).mp
    rw [map_sub, hpa, sub_self]
  have heps : augmentation R L a = augmentation R L p := by
    have h := augmentation_eq_zero_of_mem_envelopingIdeal ⁅N, N⁆ hker
    rwa [map_sub, sub_eq_zero] at h
  obtain ⟨x, hx, he⟩ := exists_polynomial_firstOrder N hp
  refine ⟨x, hx, ?_⟩
  convert Submodule.add_mem _ (mem_adicSquare_of_mem_derivedIdeal N hker) he using 1
  rw [heps]
  abel

/-- A linear-plus-polynomial representative in the derived quotient gives a linear first-order representative. -/
theorem exists_firstOrder_of_quotient_linearPolynomial (N : LieIdeal R L)
    {a : UniversalEnvelopingAlgebra R L}
    (ha : Enveloping.quotientMap ⁅N, N⁆ a ∈ linearPolynomialPart (idealAbelianImage N)) :
    ∃ x : L, a - algebraMap R _ (augmentation R L a) - ι R x ∈
      adicPower R _ (envelopingIdeal N) 2 := by
  obtain ⟨ybar, p, hp, he⟩ := (mem_linearPolynomialPart_iff (idealAbelianImage N) _).mp ha
  obtain ⟨y, hy⟩ := quotientLieHom_surjective ⁅N, N⁆ ybar
  have hp' : Enveloping.quotientMap ⁅N, N⁆ (a - ι R y) ∈
      idealPolynomialPart (idealAbelianImage N) := by
    rw [map_sub, derivedQuotientMap_ι, hy, he, add_sub_cancel_left]
    exact hp
  obtain ⟨z, hz, hez⟩ := exists_firstOrder_of_quotient_polynomial N hp'
  refine ⟨y + z, ?_⟩
  convert hez using 1
  simp only [map_sub, augmentation_ι, sub_zero, map_add]
  abel

/-- The quotient LN description also identifies the intrinsic ideal of C1. -/
theorem derivedIdeal_eq_intrinsicIdeal_of_quotient_LN (N : LieIdeal R L)
    [LieRing.IsNilpotent N]
    (hLN : LN R (UniversalEnvelopingAlgebra R (idealDerivedQuotient N)) ⊆
      idealPolynomialPart (idealAbelianImage N)) :
    envelopingIdeal ⁅N, N⁆ = intrinsicIdeal R (UniversalEnvelopingAlgebra R L) := by
  apply derivedIdeal_eq_intrinsicIdeal N
  intro a ha b hb
  have ha' := hLN (mem_LN_map_of_surjective (Enveloping.quotientMap ⁅N, N⁆)
    (Enveloping.quotientMap_surjective ⁅N, N⁆) ha)
  have hb' := hLN (mem_LN_map_of_surjective (Enveloping.quotientMap ⁅N, N⁆)
    (Enveloping.quotientMap_surjective ⁅N, N⁆) hb)
  exact (commute_of_mem_idealPolynomialPart (idealAbelianImage N) ha' hb').eq

section Field

variable {k L₁ L₂ : Type*} [Field k]
  [LieRing L₁] [LieAlgebra k L₁] [Module.Finite k L₁]
  [LieRing L₂] [LieAlgebra k L₂]

/-- The LF classification in the target metabelian quotient gives the degree-zero approximation. -/
theorem leadingApproximation_zero_of_quotient_LF
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (N' : LieIdeal k L₂)
    (hLF : LF k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N')) ⊆
      linearPolynomialPart (idealAbelianImage N'))
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    (⊤ : Submodule k L₁) ≤ leadingApproximation φ.toAlgHom N' 0 := by
  intro x hx
  have hlocal := mem_LF_map_of_surjective (Enveloping.quotientMap ⁅N', N'⁆)
    (Enveloping.quotientMap_surjective ⁅N', N'⁆)
    ((mem_LF_map_iff φ (ι k x)).mpr (ι_mem_LF (Module.finBasis k L₁) x))
  obtain ⟨y, hy⟩ := exists_firstOrder_of_quotient_linearPolynomial N' (hLF hlocal)
  have heps : augmentation k L₂ (φ (ι k x)) = 0 := by
    have h := DFunLike.congr_fun hε (ι k x)
    simpa only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom, augmentation_ι] using h
  refine ⟨y, LieSubmodule.mem_top _, ?_⟩
  have hy' : φ (ι k x) - ι k y ∈ adicPower k _ (envelopingIdeal N') 2 := by
    simpa only [heps, map_zero, sub_zero] using hy
  exact adicPower_antitone (envelopingIdeal N') (by decide : 1 ≤ 2) hy'

omit [Module.Finite k L₁] in
/-- The LN classification in the target quotient gives the constant linear first layer. -/
theorem leadingApproximation_one_of_quotient_LN
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (N : LieIdeal k L₁) [LieRing.IsNilpotent N] (N' : LieIdeal k L₂)
    (hLN : LN k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N')) ⊆
      idealPolynomialPart (idealAbelianImage N'))
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    N.toSubmodule ≤ leadingApproximation φ.toAlgHom N' 1 := by
  intro x hx
  have hlocal := mem_LN_map_of_surjective (Enveloping.quotientMap ⁅N', N'⁆)
    (Enveloping.quotientMap_surjective ⁅N', N'⁆)
    ((mem_LN_map_iff φ (ι k x)).mpr (ι_mem_LN_of_mem_nilpotentIdeal N hx))
  obtain ⟨y, hyN, hy⟩ := exists_firstOrder_of_quotient_polynomial N' (hLN hlocal)
  have heps : augmentation k L₂ (φ (ι k x)) = 0 := by
    have h := DFunLike.congr_fun hε (ι k x)
    simpa only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom, augmentation_ι] using h
  refine ⟨y, hyN, ?_⟩
  change φ (ι k x) - ι k y ∈ adicPower k _ (envelopingIdeal N') 2
  simpa only [heps, map_zero, sub_zero] using hy

omit [Module.Finite k L₁] in
/-- Augmentation preservation is inherited by the inverse equivalence. -/
theorem augmentation_preserving_symm
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    (augmentation k L₁).comp φ.symm.toAlgHom = augmentation k L₂ := by
  apply AlgHom.ext
  intro a
  have h := DFunLike.congr_fun hε (φ.symm a)
  simpa only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom, AlgEquiv.apply_symm_apply] using h.symm

variable [Module.Finite k L₂]

/-- Both quotient descriptions give exactly the four inputs of `LeadingTerms`. -/
theorem initial_approximations_of_quotient_descriptions
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (N : LieIdeal k L₁) [LieRing.IsNilpotent N] (N' : LieIdeal k L₂) [LieRing.IsNilpotent N']
    (hLN : LN k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N)) ⊆
      idealPolynomialPart (idealAbelianImage N))
    (hLF : LF k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N)) ⊆
      linearPolynomialPart (idealAbelianImage N))
    (hLN' : LN k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N')) ⊆
      idealPolynomialPart (idealAbelianImage N'))
    (hLF' : LF k (UniversalEnvelopingAlgebra k (idealDerivedQuotient N')) ⊆
      linearPolynomialPart (idealAbelianImage N'))
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    (⊤ : Submodule k L₁) ≤ leadingApproximation φ.toAlgHom N' 0 ∧
      N.toSubmodule ≤ leadingApproximation φ.toAlgHom N' 1 ∧
      (⊤ : Submodule k L₂) ≤ leadingApproximation φ.symm.toAlgHom N 0 ∧
      N'.toSubmodule ≤ leadingApproximation φ.symm.toAlgHom N 1 :=
  ⟨leadingApproximation_zero_of_quotient_LF φ N' hLF' hε,
    leadingApproximation_one_of_quotient_LN φ N N' hLN' hε,
    leadingApproximation_zero_of_quotient_LF φ.symm N hLF (augmentation_preserving_symm φ hε),
    leadingApproximation_one_of_quotient_LN φ.symm N' N hLN (augmentation_preserving_symm φ hε)⟩

/-- The complete initial-approximation assembly over an algebraically closed field. -/
theorem initial_approximations_of_isAlgClosed [CharZero k] [IsAlgClosed k]
    [LieAlgebra.IsSolvable L₁]
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    (⊤ : Submodule k L₁) ≤ leadingApproximation φ.toAlgHom (nilradical k L₂) 0 ∧
      (nilradical k L₁).toSubmodule ≤ leadingApproximation φ.toAlgHom (nilradical k L₂) 1 ∧
      (⊤ : Submodule k L₂) ≤ leadingApproximation φ.symm.toAlgHom (nilradical k L₁) 0 ∧
      (nilradical k L₂).toSubmodule ≤ leadingApproximation φ.symm.toAlgHom (nilradical k L₁) 1 := by
  haveI : LieAlgebra.IsSolvable L₂ := isSolvable_of_enveloping_equiv φ
  apply initial_approximations_of_quotient_descriptions φ (nilradical k L₁) (nilradical k L₂)
  · intro a ha
    exact (hq2_nilradical_derivedQuotient a).1.mp ha
  · intro a ha
    exact (mem_linearPolynomialPart_iff _ a).mpr ((hq2_nilradical_derivedQuotient a).2.mp ha)
  · intro a ha
    exact (hq2_nilradical_derivedQuotient a).1.mp ha
  · intro a ha
    exact (mem_linearPolynomialPart_iff _ a).mpr ((hq2_nilradical_derivedQuotient a).2.mp ha)
  · exact hε

/-- C1 over the original field: the intrinsic associative ideal is exactly `U[N,N]`. -/
theorem nilradical_derivedIdeal_eq_intrinsicIdeal [CharZero k] [LieAlgebra.IsSolvable L₁] :
    envelopingIdeal ⁅nilradical k L₁, nilradical k L₁⁆ =
      intrinsicIdeal k (UniversalEnvelopingAlgebra k L₁) :=
  derivedIdeal_eq_intrinsicIdeal_of_quotient_LN (nilradical k L₁)
    (LN_subset_polynomialPart_nilradical_derivedQuotient (k := k) (L := L₁))

/-- The original associative equivalence preserves the nilradical-derived ideals, without augmentation hypotheses. -/
theorem map_nilradical_derivedIdeal [CharZero k] [LieAlgebra.IsSolvable L₁]
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂) :
    TwoSidedIdeal.map φ.toAlgHom (envelopingIdeal ⁅nilradical k L₁, nilradical k L₁⁆) =
      envelopingIdeal ⁅nilradical k L₂, nilradical k L₂⁆ := by
  haveI : LieAlgebra.IsSolvable L₂ := isSolvable_of_enveloping_equiv φ
  rw [nilradical_derivedIdeal_eq_intrinsicIdeal, nilradical_derivedIdeal_eq_intrinsicIdeal]
  exact map_intrinsicIdeal φ

/-- Over any characteristic-zero field, an augmentation-preserving UEA equivalence
gives the four initial linear approximations required by `LeadingTerms`.
Only the source is assumed solvable; target solvability is proved from the equivalence. -/
theorem initial_approximations [CharZero k] [LieAlgebra.IsSolvable L₁]
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂)
    (hε : (augmentation k L₂).comp φ.toAlgHom = augmentation k L₁) :
    (⊤ : Submodule k L₁) ≤ leadingApproximation φ.toAlgHom (nilradical k L₂) 0 ∧
      (nilradical k L₁).toSubmodule ≤ leadingApproximation φ.toAlgHom (nilradical k L₂) 1 ∧
      (⊤ : Submodule k L₂) ≤ leadingApproximation φ.symm.toAlgHom (nilradical k L₁) 0 ∧
      (nilradical k L₂).toSubmodule ≤ leadingApproximation φ.symm.toAlgHom (nilradical k L₁) 1 := by
  haveI : LieAlgebra.IsSolvable L₂ := isSolvable_of_enveloping_equiv φ
  exact initial_approximations_of_quotient_descriptions φ (nilradical k L₁) (nilradical k L₂)
    (LN_subset_polynomialPart_nilradical_derivedQuotient (k := k) (L := L₁))
    (LF_subset_linearPolynomialPart_nilradical_derivedQuotient (k := k) (L := L₁))
    (LN_subset_polynomialPart_nilradical_derivedQuotient (k := k) (L := L₂))
    (LF_subset_linearPolynomialPart_nilradical_derivedQuotient (k := k) (L := L₂)) hε

/-- The explicit standard normalization supplies the initial approximations for any original equivalence. -/
theorem initial_approximations_normalized [CharZero k] [LieAlgebra.IsSolvable L₁]
    (φ : UniversalEnvelopingAlgebra k L₁ ≃ₐ[k] UniversalEnvelopingAlgebra k L₂) :
    (⊤ : Submodule k L₁) ≤ leadingApproximation (normalized φ).toAlgHom (nilradical k L₂) 0 ∧
      (nilradical k L₁).toSubmodule ≤
        leadingApproximation (normalized φ).toAlgHom (nilradical k L₂) 1 ∧
      (⊤ : Submodule k L₂) ≤
        leadingApproximation (normalized φ).symm.toAlgHom (nilradical k L₁) 0 ∧
      (nilradical k L₂).toSubmodule ≤
        leadingApproximation (normalized φ).symm.toAlgHom (nilradical k L₁) 1 :=
  initial_approximations (normalized φ) (normalized_preserves_augmentation φ)

end Field

end EnvelopingIsomorphism.Identification
