import EnvelopingIsomorphism.Identification.LocallyFinite
import EnvelopingIsomorphism.Identification.LocallyNilpotent
import EnvelopingIsomorphism.Enveloping.Quotient
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel

/-! The associative ideal intrinsically generated by commutators of locally
nilpotent inner elements. Its comparison with the nilradical-derived ideal
is supplied by the metabelian classification. -/

namespace EnvelopingIsomorphism.Identification

universe u v w
variable (R : Type u) [CommRing R]
variable (A : Type v) [Ring A] [Algebra R A]

/-- Generators of the intrinsic commutator ideal. -/
def lnCommutators : Set A :=
  {z | ∃ a ∈ LN R A, ∃ b ∈ LN R A, z = a * b - b * a}

/-- This ideal uses only the associative algebra and its scalar structure. -/
def intrinsicIdeal : TwoSidedIdeal A := TwoSidedIdeal.span (lnCommutators R A)

variable {R A}
variable {B : Type w} [Ring B] [Algebra R B]

theorem commutator_mem_intrinsicIdeal {a b : A}
    (ha : a ∈ LN R A) (hb : b ∈ LN R A) :
    a * b - b * a ∈ intrinsicIdeal R A :=
  TwoSidedIdeal.subset_span ⟨a, ha, b, hb, rfl⟩

theorem intrinsicIdeal_le_comap (f : A →ₐ[R] B) (hf : Function.Surjective f) :
    intrinsicIdeal R A ≤ (intrinsicIdeal R B).comap f := by
  apply TwoSidedIdeal.span_le.mpr
  rintro z ⟨a, ha, b, hb, rfl⟩
  change a * b - b * a ∈ (intrinsicIdeal R B).comap f
  apply (TwoSidedIdeal.mem_comap f).mpr
  simpa only [map_sub, map_mul] using
    commutator_mem_intrinsicIdeal
      (mem_LN_map_of_surjective f hf ha) (mem_LN_map_of_surjective f hf hb)

theorem mem_intrinsicIdeal_map_iff (e : A ≃ₐ[R] B) (a : A) :
    e a ∈ intrinsicIdeal R B ↔ a ∈ intrinsicIdeal R A := by
  constructor
  · intro h
    have h' := (TwoSidedIdeal.mem_comap e.symm.toAlgHom).mp
      (intrinsicIdeal_le_comap e.symm.toAlgHom e.symm.surjective h)
    simpa only [AlgEquiv.coe_toAlgHom,
      AlgEquiv.symm_apply_apply] using h'
  · intro h
    exact (TwoSidedIdeal.mem_comap e.toAlgHom).mp
      (intrinsicIdeal_le_comap e.toAlgHom e.surjective h)

/-- The intrinsic ideal is preserved by the original associative equivalence,
without any augmentation or filtration hypothesis. -/
theorem map_intrinsicIdeal (e : A ≃ₐ[R] B) :
    TwoSidedIdeal.map e.toAlgHom (intrinsicIdeal R A) = intrinsicIdeal R B := by
  apply le_antisymm
  · apply TwoSidedIdeal.span_le.mpr
    rintro z ⟨a, ha, rfl⟩
    exact (mem_intrinsicIdeal_map_iff e a).mpr ha
  · intro z hz
    apply TwoSidedIdeal.subset_span
    refine ⟨e.symm z, ?_, e.apply_symm_apply z⟩
    exact (mem_intrinsicIdeal_map_iff e.symm z).mpr hz

/-- To bound this ideal by a quotient kernel, it suffices that the images of
locally nilpotent elements commute in that quotient. -/
theorem intrinsicIdeal_le_ker (f : A →ₐ[R] B)
    (hcomm : ∀ a ∈ LN R A, ∀ b ∈ LN R A, f a * f b = f b * f a) :
    intrinsicIdeal R A ≤ TwoSidedIdeal.ker f := by
  apply TwoSidedIdeal.span_le.mpr
  rintro z ⟨a, ha, b, hb, rfl⟩
  change a * b - b * a ∈ TwoSidedIdeal.ker f
  rw [TwoSidedIdeal.mem_ker, map_sub, map_mul, map_mul, hcomm a ha b hb, sub_self]

section Lie

variable {L : Type v} [LieRing L] [LieAlgebra R L]
attribute [local instance 100] LieRing.ofAssociativeRing

/-- The ideal generated by the derived ideal of any nilpotent Lie ideal lies
in the intrinsic associative ideal, by A5. -/
theorem derivedIdeal_le_intrinsicIdeal (N : LieIdeal R L) [LieRing.IsNilpotent N] :
    Enveloping.lieIdealGenerated ⁅N, N⁆ ≤
      intrinsicIdeal R (UniversalEnvelopingAlgebra R L) := by
  let J := intrinsicIdeal R (UniversalEnvelopingAlgebra R L)
  let K : Submodule R L :=
    (J.asIdeal.restrictScalars R).comap (UniversalEnvelopingAlgebra.ι R).toLinearMap
  have hK : (⁅N, N⁆ : LieIdeal R L).toSubmodule ≤ K := by
    rw [LieSubmodule.lieIdeal_oper_eq_linear_span']
    apply Submodule.span_le.mpr
    rintro z ⟨x, hx, y, hy, rfl⟩
    change UniversalEnvelopingAlgebra.ι R ⁅x, y⁆ ∈ J
    have h := commutator_mem_intrinsicIdeal
      (ι_mem_LN_of_mem_nilpotentIdeal N hx)
      (ι_mem_LN_of_mem_nilpotentIdeal N hy)
    simpa only [LieHom.map_lie, Ring.lie_def] using h
  apply TwoSidedIdeal.span_le.mpr
  rintro z ⟨x, hx, rfl⟩
  exact hK hx

/-- The metabelian classification needs to provide only the stated
commutativity of quotient images to identify the intrinsic ideal exactly. -/
theorem derivedIdeal_eq_intrinsicIdeal (N : LieIdeal R L) [LieRing.IsNilpotent N]
    (hcomm : ∀ a ∈ LN R (UniversalEnvelopingAlgebra R L),
      ∀ b ∈ LN R (UniversalEnvelopingAlgebra R L),
      Enveloping.quotientMap ⁅N, N⁆ a * Enveloping.quotientMap ⁅N, N⁆ b =
      Enveloping.quotientMap ⁅N, N⁆ b * Enveloping.quotientMap ⁅N, N⁆ a) :
    Enveloping.lieIdealGenerated ⁅N, N⁆ =
      intrinsicIdeal R (UniversalEnvelopingAlgebra R L) := by
  apply le_antisymm (derivedIdeal_le_intrinsicIdeal N)
  rw [← Enveloping.ker_quotientMap]
  exact intrinsicIdeal_le_ker _ hcomm

end Lie

end EnvelopingIsomorphism.Identification
