import EnvelopingIsomorphism.Identification.LocallyNilpotent
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-! The intrinsic polynomial subalgebra associated to an abelian Lie ideal.
These native-enveloping lemmas form the first part of the HQ2 proof. -/

noncomputable section

namespace EnvelopingIsomorphism.Identification

universe u v
variable {R : Type u} [CommRing R]
variable {L : Type v} [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing
open UniversalEnvelopingAlgebra

/-- The subalgebra generated by the actual images of an ideal in the native UEA. -/
def idealPolynomialPart (H : LieIdeal R L) : Subalgebra R (UniversalEnvelopingAlgebra R L) :=
  Algebra.adjoin R (Set.range (fun h : H => ι R (h : L)))

/-- The concrete linear space used by the LF description of HQ2. -/
def linearPolynomialPart (H : LieIdeal R L) : Submodule R (UniversalEnvelopingAlgebra R L) :=
  (ι R).toLinearMap.range ⊔ (idealPolynomialPart H).toSubmodule

theorem mem_linearPolynomialPart_iff (H : LieIdeal R L)
    (a : UniversalEnvelopingAlgebra R L) :
    a ∈ linearPolynomialPart H ↔
      ∃ x : L, ∃ p, p ∈ idealPolynomialPart H ∧ a = ι R x + p := by
  constructor
  · intro ha
    obtain ⟨u, hu, p, hp, heq⟩ := Submodule.mem_sup.mp ha
    obtain ⟨x, rfl⟩ := hu
    exact ⟨x, p, hp, heq.symm⟩
  · rintro ⟨x, p, hp, rfl⟩
    exact Submodule.mem_sup.mpr ⟨ι R x, ⟨x, rfl⟩, p, hp, rfl⟩

theorem ι_mem_idealPolynomialPart (H : LieIdeal R L) {x : L} (hx : x ∈ H) :
    ι R x ∈ idealPolynomialPart H := Algebra.subset_adjoin ⟨⟨x, hx⟩, rfl⟩

theorem inner_mul (a x y : UniversalEnvelopingAlgebra R L) :
    ⁅a, x * y⁆ = ⁅a, x⁆ * y + x * ⁅a, y⁆ := by
  simp only [Ring.lie_def, mul_sub, sub_mul, mul_assoc]
  abel

/-- Adjoint action of the ambient Lie algebra preserves its ideal's
generated associative subalgebra. -/
theorem lie_mem_idealPolynomialPart (H : LieIdeal R L) (x : L)
    {p : UniversalEnvelopingAlgebra R L} (hp : p ∈ idealPolynomialPart H) :
    ⁅ι R x, p⁆ ∈ idealPolynomialPart H := by
  induction hp using Algebra.adjoin_induction with
  | mem p hp =>
    obtain ⟨h, rfl⟩ := hp
    rw [← LieHom.map_lie]
    exact ι_mem_idealPolynomialPart H (H.lie_mem h.property)
  | algebraMap r =>
    have hz : ⁅ι R x, algebraMap R (UniversalEnvelopingAlgebra R L) r⁆ = 0 := by
      simp [Ring.lie_def, Algebra.commutes]
    rw [hz]
    exact zero_mem _
  | add p q _ _ hp hq =>
    rw [lie_add]
    exact add_mem hp hq
  | mul p q hp hq hp' hq' =>
    rw [inner_mul]
    exact add_mem (mul_mem hp' hq) (mul_mem hp hq')

theorem commute_ι_of_abelianIdeal (H : LieIdeal R L) [IsLieAbelian H] (x y : H) :
    Commute (ι R (x : L)) (ι R (y : L)) := by
  change ι R (x : L) * ι R (y : L) = ι R (y : L) * ι R (x : L)
  rw [← sub_eq_zero, ← Ring.lie_def, ← LieHom.map_lie]
  have hzero : ⁅(x : L), (y : L)⁆ = 0 :=
    congrArg (fun h : H => (h : L)) (trivial_lie_zero H H x y)
  rw [hzero, map_zero]

/-- The polynomial part of an abelian ideal is commutative inside the original UEA. -/
theorem commute_of_mem_idealPolynomialPart (H : LieIdeal R L) [IsLieAbelian H]
    {p q : UniversalEnvelopingAlgebra R L}
    (hp : p ∈ idealPolynomialPart H) (hq : q ∈ idealPolynomialPart H) : Commute p q := by
  apply Algebra.commute_of_mem_adjoin_of_forall_mem_commute hq
  rintro _ ⟨y, rfl⟩
  apply Commute.symm
  apply Algebra.commute_of_mem_adjoin_of_forall_mem_commute hp
  rintro _ ⟨x, rfl⟩
  exact commute_ι_of_abelianIdeal H y x

theorem lie_eq_zero_of_mem_idealPolynomialPart (H : LieIdeal R L) [IsLieAbelian H]
    {p q : UniversalEnvelopingAlgebra R L}
    (hp : p ∈ idealPolynomialPart H) (hq : q ∈ idealPolynomialPart H) : ⁅p, q⁆ = 0 := by
  rw [Ring.lie_def, (commute_of_mem_idealPolynomialPart H hp hq).eq, sub_self]

/-- Local nilpotence on Lie generators extends to all of their enveloping algebra. -/
theorem mem_LN_of_locallyNilpotent_on_generators (a : UniversalEnvelopingAlgebra R L)
    (ha : ∀ x : L, ∃ n : ℕ, (LieAlgebra.ad R _ a ^ n) (ι R x) = 0) :
    a ∈ LN R (UniversalEnvelopingAlgebra R L) := by
  let D := LieAlgebra.ad R (UniversalEnvelopingAlgebra R L) a
  have hD (p q : UniversalEnvelopingAlgebra R L) :
      D (p * q) = D p * q + p * D q := inner_mul a p q
  intro p
  induction p using EnvelopingIsomorphism.Enveloping.induction with
  | scalar r =>
    refine ⟨1, ?_⟩
    simp [LieAlgebra.ad_apply, Ring.lie_def, Algebra.commutes]
  | generator x => exact ha x
  | mul p q hp hq =>
    obtain ⟨n, hn⟩ := hp
    obtain ⟨m, hm⟩ := hq
    exact ⟨n + m, pow_mul_eq_zero D hD hn hm⟩
  | add p q hp hq =>
    obtain ⟨n, hn⟩ := hp
    obtain ⟨m, hm⟩ := hq
    exact ⟨n + m, by rw [map_add,
      pow_apply_eq_zero_of_le D hn (Nat.le_add_right n m),
      pow_apply_eq_zero_of_le D hm (Nat.le_add_left m n), add_zero]⟩

/-- The easy inclusion in HQ2: every polynomial in an abelian ideal has
locally nilpotent inner derivation. No hypothesis on the quotient is needed. -/
theorem idealPolynomialPart_subset_LN (H : LieIdeal R L) [IsLieAbelian H] :
    (idealPolynomialPart H : Set (UniversalEnvelopingAlgebra R L)) ⊆
      LN R (UniversalEnvelopingAlgebra R L) := by
  intro p hp
  apply mem_LN_of_locallyNilpotent_on_generators p
  intro x
  refine ⟨2, ?_⟩
  change ⁅p, ⁅p, ι R x⁆⁆ = 0
  apply lie_eq_zero_of_mem_idealPolynomialPart H hp
  rw [← lie_skew p (ι R x)]
  exact neg_mem (lie_mem_idealPolynomialPart H x hp)

theorem idealPolynomialPart_subset_LF (H : LieIdeal R L) [IsLieAbelian H] :
    (idealPolynomialPart H : Set (UniversalEnvelopingAlgebra R L)) ⊆
      LF R (UniversalEnvelopingAlgebra R L) :=
  fun _ hp => LN_subset_LF (idealPolynomialPart_subset_LN H hp)

end EnvelopingIsomorphism.Identification
