import Mathlib.RingTheory.PowerSeries.Substitution
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.Algebra.Algebra.Rat
import Mathlib.Algebra.Module.Rat

/-! Scalar formal series may be evaluated at one nilpotent element of an
arbitrary noncommutative rational algebra: the algebra generated by that one
element is commutative. This file makes that reduction explicit. -/

noncomputable section

namespace EnvelopingIsomorphism.FormalSeries

open PowerSeries

section Commutative

variable {A : Type*} [CommRing A] [Algebra ℚ A]

theorem hasSubst_C_of_isNilpotent {x : A} (hx : IsNilpotent x) :
    PowerSeries.HasSubst (C x) := by
  simpa [PowerSeries.HasSubst, ← PowerSeries.constantCoeff_eq] using hx

/-- Evaluation at a nilpotent element of a commutative rational algebra. -/
def commNilEval {x : A} (hx : IsNilpotent x) : PowerSeries ℚ →+* A :=
  PowerSeries.constantCoeff.comp
    (PowerSeries.substAlgHom (hasSubst_C_of_isNilpotent hx)).toRingHom

theorem commNilEval_apply {x : A} (hx : IsNilpotent x) (F : PowerSeries ℚ) :
    commNilEval hx F = constantCoeff (F.subst (C x)) := by
  simp only [commNilEval, RingHom.comp_apply, AlgHom.toRingHom_eq_coe,
    RingHom.coe_coe, PowerSeries.coe_substAlgHom]

/-- Nilpotent evaluation is a finite sum, with any valid nilpotence bound. -/
theorem commNilEval_eq_sum {x : A} (hx : IsNilpotent x) {N : ℕ} (hN : x ^ N = 0)
    (F : PowerSeries ℚ) :
    commNilEval hx F = ∑ i ∈ Finset.range N, coeff i F • x ^ i := by
  rw [commNilEval_apply, ← coeff_zero_eq_constantCoeff,
    PowerSeries.coeff_subst' (hasSubst_C_of_isNilpotent hx)]
  simp only [coeff_zero_eq_constantCoeff, map_pow, constantCoeff_C]
  apply finsum_eq_sum_of_support_subset
  intro i hi
  by_contra hiN
  have hzero : x ^ i = 0 := pow_eq_zero_of_le (by simpa using hiN) hN
  simpa [Function.mem_support, hzero] using hi

@[simp] theorem commNilEval_X {x : A} (hx : IsNilpotent x) :
    commNilEval hx X = x := by
  rw [commNilEval_apply, PowerSeries.subst_X (hasSubst_C_of_isNilpotent hx), constantCoeff_C]

theorem subst_C_eq_C_commNilEval {x : A} (hx : IsNilpotent x) (F : PowerSeries ℚ) :
    F.subst (C x) = C (commNilEval hx F) := by
  ext n
  cases n with
  | zero => simp [commNilEval_apply]
  | succ n =>
    rw [PowerSeries.coeff_subst' (hasSubst_C_of_isNilpotent hx)]
    simp only [← map_pow, coeff_C, Nat.succ_ne_zero, if_false, smul_zero,
      finsum_zero]

/-- A scalar series with zero constant term takes nilpotent values at
nilpotent arguments. -/
theorem isNilpotent_commNilEval {x : A} (hx : IsNilpotent x) {G : PowerSeries ℚ}
    (hG : constantCoeff G = 0) : IsNilpotent (commNilEval hx G) := by
  have h := (PowerSeries.HasSubst.of_constantCoeff_zero' hG).comp
    (hasSubst_C_of_isNilpotent hx)
  rw [commNilEval_apply]
  simpa only [PowerSeries.HasSubst, PowerSeries.coe_substAlgHom,
    ← PowerSeries.constantCoeff_eq] using h

/-- Nilpotent evaluation respects formal substitution. -/
theorem commNilEval_subst {x : A} (hx : IsNilpotent x) (F : PowerSeries ℚ)
    {G : PowerSeries ℚ} (hG : constantCoeff G = 0) :
    commNilEval hx (F.subst G) =
      commNilEval (isNilpotent_commNilEval hx hG) F := by
  calc
    commNilEval hx (F.subst G) =
        constantCoeff (PowerSeries.subst (C x) (PowerSeries.subst G F)) :=
      commNilEval_apply _ _
    _ = constantCoeff (F.subst (G.subst (C x))) := congrArg constantCoeff
      (PowerSeries.subst_comp_subst_apply (R := ℚ) (S := ℚ) (T := A)
        (PowerSeries.HasSubst.of_constantCoeff_zero' hG) (hasSubst_C_of_isNilpotent hx) F)
    _ = constantCoeff (F.subst (C (commNilEval hx G))) :=
      congrArg (fun z : PowerSeries A ↦ constantCoeff (F.subst z))
        (subst_C_eq_C_commNilEval hx G)
    _ = commNilEval (isNilpotent_commNilEval hx hG) F := (commNilEval_apply _ _).symm

end Commutative

section Noncommutative

variable {R : Type*} [Ring R] [Algebra ℚ R]

/-- The distinguished generator of the commutative algebra generated by `x`. -/
def adjoinGenerator (x : R) : Algebra.adjoin ℚ ({x} : Set R) :=
  ⟨x, Algebra.subset_adjoin (by simp)⟩

@[simp] theorem coe_adjoinGenerator (x : R) : (adjoinGenerator x : R) = x := rfl

theorem isNilpotent_adjoinGenerator {x : R} (hx : IsNilpotent x) :
    IsNilpotent (adjoinGenerator x) := by
  obtain ⟨N, hN⟩ := hx
  refine ⟨N, Subtype.ext ?_⟩
  exact hN

/-- Evaluate scalar formal series in a noncommutative ring at a nilpotent
element, through the commutative subalgebra generated by that element. -/
def nilEval {x : R} (hx : IsNilpotent x) : PowerSeries ℚ →+* R :=
  (Algebra.adjoin ℚ ({x} : Set R)).val.toRingHom.comp
    (commNilEval (isNilpotent_adjoinGenerator hx))

theorem nilEval_congr {x y : R} (hx : IsNilpotent x) (hy : IsNilpotent y)
    (hxy : x = y) (F : PowerSeries ℚ) : nilEval hx F = nilEval hy F := by
  subst y
  rfl

/-- The reduction through the generated algebra has the expected finite-sum
formula in the original noncommutative ring. -/
theorem nilEval_eq_sum {x : R} (hx : IsNilpotent x) {N : ℕ} (hN : x ^ N = 0)
    (F : PowerSeries ℚ) :
    nilEval hx F = ∑ i ∈ Finset.range N, coeff i F • x ^ i := by
  change ((Algebra.adjoin ℚ ({x} : Set R)).val
    (commNilEval (isNilpotent_adjoinGenerator hx) F)) = _
  rw [commNilEval_eq_sum _ (show adjoinGenerator x ^ N = 0 from Subtype.ext hN), map_sum]
  apply Finset.sum_congr rfl
  intro i hi
  simp only [map_smul, map_pow, coe_adjoinGenerator]
  rfl

/-- Scalar nilpotent evaluation is natural under ring homomorphisms. -/
theorem nilEval_map {S : Type*} [Ring S] [Algebra ℚ S] (f : R →+* S)
    {x : R} (hx : IsNilpotent x) (F : PowerSeries ℚ) :
    nilEval (hx.map f) F = f (nilEval hx F) := by
  obtain ⟨N, hN⟩ := hx
  rw [nilEval_eq_sum _ (show (f x) ^ N = 0 by rw [← map_pow, hN, map_zero]),
    nilEval_eq_sum _ hN, map_sum]
  apply Finset.sum_congr rfl
  intro i hi
  rw [map_rat_smul, map_pow]

@[simp] theorem nilEval_X {x : R} (hx : IsNilpotent x) : nilEval hx X = x := by
  change ((Algebra.adjoin ℚ ({x} : Set R)).val
    (commNilEval (isNilpotent_adjoinGenerator hx) X)) = x
  rw [commNilEval_X]
  rfl

end Noncommutative

section CommutativeComparison

variable {A : Type*} [CommRing A] [Algebra ℚ A]

theorem nilEval_eq_commNilEval {x : A} (hx : IsNilpotent x) (F : PowerSeries ℚ) :
    nilEval hx F = commNilEval hx F := by
  obtain ⟨N, hN⟩ := hx
  rw [nilEval_eq_sum _ hN, commNilEval_eq_sum _ hN]

end CommutativeComparison

section NoncommutativeComposition

variable {R : Type*} [Ring R] [Algebra ℚ R]

theorem isNilpotent_nilEval {x : R} (hx : IsNilpotent x) {G : PowerSeries ℚ}
    (hG : constantCoeff G = 0) : IsNilpotent (nilEval hx G) :=
  (isNilpotent_commNilEval (isNilpotent_adjoinGenerator hx) hG).map
    (Algebra.adjoin ℚ ({x} : Set R)).val.toRingHom

/-- Formal substitution at a nilpotent element of a noncommutative ring is
still associative, since all series involved use the same single generator. -/
theorem nilEval_subst {x : R} (hx : IsNilpotent x) (F : PowerSeries ℚ)
    {G : PowerSeries ℚ} (hG : constantCoeff G = 0) :
    nilEval hx (F.subst G) = nilEval (isNilpotent_nilEval hx hG) F := by
  change ((Algebra.adjoin ℚ ({x} : Set R)).val
    (commNilEval (isNilpotent_adjoinGenerator hx) (F.subst G))) = _
  rw [commNilEval_subst _ _ hG, ← nilEval_eq_commNilEval]
  exact (nilEval_map (Algebra.adjoin ℚ ({x} : Set R)).val.toRingHom
    (isNilpotent_commNilEval (isNilpotent_adjoinGenerator hx) hG) F).symm

end NoncommutativeComposition

end EnvelopingIsomorphism.FormalSeries
