import EnvelopingIsomorphism.Enveloping.UniversalProperties
import Mathlib.Algebra.Lie.Quotient
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-! Enveloping algebras of Lie quotients, using universal properties only. -/

namespace EnvelopingIsomorphism.Enveloping

open UniversalEnvelopingAlgebra

universe u v w
variable {R : Type u} [CommRing R]
variable {L : Type v} [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The canonical map to the quotient by a native Lie ideal. -/
def lieQuotientMap (H : LieIdeal R L) : L →ₗ⁅R⁆ L ⧸ H where
  toLinearMap := H.toSubmodule.mkQ
  map_lie' := rfl

@[simp] theorem lieQuotientMap_apply (H : LieIdeal R L) (x : L) :
    lieQuotientMap H x = LieSubmodule.Quotient.mk x := rfl

theorem lieQuotientMap_surjective (H : LieIdeal R L) :
    Function.Surjective (lieQuotientMap H) := Quot.mk_surjective

@[simp] theorem lieQuotientMap_eq_zero_iff (H : LieIdeal R L) (x : L) :
    lieQuotientMap H x = 0 ↔ x ∈ H :=
  LieSubmodule.Quotient.mk_eq_zero'

@[simp] theorem lieQuotientMap_ker (H : LieIdeal R L) : (lieQuotientMap H).ker = H := by
  ext x
  exact lieQuotientMap_eq_zero_iff H x

/-- The universal property of a Lie quotient, bundled as a Lie homomorphism. -/
def liftLieQuotient (H : LieIdeal R L) {A : Type w} [LieRing A] [LieAlgebra R A]
    (f : L →ₗ⁅R⁆ A) (hH : H ≤ f.ker) : L ⧸ H →ₗ⁅R⁆ A where
  toLinearMap := H.toSubmodule.liftQ f.toLinearMap hH
  map_lie' {x y} := by
    induction x using Submodule.Quotient.induction_on with | _ x
    induction y using Submodule.Quotient.induction_on with | _ y
    exact f.map_lie x y

@[simp] theorem liftLieQuotient_mk (H : LieIdeal R L)
    {A : Type w} [LieRing A] [LieAlgebra R A]
    (f : L →ₗ⁅R⁆ A) (hH : H ≤ f.ker) (x : L) :
    liftLieQuotient H f hH (lieQuotientMap H x) = f x := rfl

/-- The two-sided ideal generated by a Lie ideal inside the standard UEA. -/
def lieIdealGenerated (H : LieIdeal R L) : TwoSidedIdeal (UniversalEnvelopingAlgebra R L) :=
  TwoSidedIdeal.span (ι R '' (H : Set L))

theorem ι_mem_lieIdealGenerated (H : LieIdeal R L) {x : L} (hx : x ∈ H) :
    ι R x ∈ lieIdealGenerated H :=
  TwoSidedIdeal.subset_span ⟨x, hx, rfl⟩

/-- The canonical map of enveloping algebras induced by a Lie quotient. -/
def quotientMap (H : LieIdeal R L) :
    UniversalEnvelopingAlgebra R L →ₐ[R] UniversalEnvelopingAlgebra R (L ⧸ H) :=
  map (lieQuotientMap H)

@[simp] theorem quotientMap_ι (H : LieIdeal R L) (x : L) :
    quotientMap H (ι R x) = ι R (lieQuotientMap H x) :=
  map_ι (lieQuotientMap H) x

theorem quotientMap_surjective (H : LieIdeal R L) :
    Function.Surjective (quotientMap H) :=
  map_surjective (lieQuotientMap H) (lieQuotientMap_surjective H)

theorem lieIdealGenerated_le_ker_quotientMap (H : LieIdeal R L) :
    lieIdealGenerated H ≤ TwoSidedIdeal.ker (quotientMap H) := by
  apply TwoSidedIdeal.span_le.mpr
  rintro _ ⟨x, hx, rfl⟩
  change ι R x ∈ TwoSidedIdeal.ker (quotientMap H)
  rw [TwoSidedIdeal.mem_ker, quotientMap_ι, (lieQuotientMap_eq_zero_iff H x).mpr hx, map_zero]

/-- The canonical map out of the associative quotient. -/
def quotientForward (H : LieIdeal R L) :
    (UniversalEnvelopingAlgebra R L ⧸ (lieIdealGenerated H).asIdeal) →ₐ[R]
      UniversalEnvelopingAlgebra R (L ⧸ H) :=
  Ideal.Quotient.liftₐ (lieIdealGenerated H).asIdeal (quotientMap H) fun _x hx ↦
    (TwoSidedIdeal.mem_ker (quotientMap H)).mp (lieIdealGenerated_le_ker_quotientMap H hx)

@[simp] theorem quotientForward_mk (H : LieIdeal R L) (x : UniversalEnvelopingAlgebra R L) :
    quotientForward H (Ideal.Quotient.mk (lieIdealGenerated H).asIdeal x) =
      quotientMap H x := rfl

private theorem lieIdeal_le_ker_quotient_ι (H : LieIdeal R L) :
    H ≤ ((Ideal.Quotient.mkₐ R (lieIdealGenerated H).asIdeal).toLieHom.comp (ι R)).ker := by
  intro x hx
  change Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x) = 0
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (ι_mem_lieIdealGenerated H hx)

/-- Quotient Lie generators inside the associative quotient. -/
def quotientGenerator (H : LieIdeal R L) :
    L ⧸ H →ₗ⁅R⁆ (UniversalEnvelopingAlgebra R L ⧸ (lieIdealGenerated H).asIdeal) :=
  liftLieQuotient H
    ((Ideal.Quotient.mkₐ R (lieIdealGenerated H).asIdeal).toLieHom.comp (ι R))
    (lieIdeal_le_ker_quotient_ι H)

@[simp] theorem quotientGenerator_mk (H : LieIdeal R L) (x : L) :
    quotientGenerator H (lieQuotientMap H x) =
      Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x) := rfl

/-- The reverse algebra map, supplied by the UEA universal property. -/
def quotientBackward (H : LieIdeal R L) : UniversalEnvelopingAlgebra R (L ⧸ H) →ₐ[R]
    (UniversalEnvelopingAlgebra R L ⧸ (lieIdealGenerated H).asIdeal) :=
  lift R (quotientGenerator H)

@[simp] theorem quotientBackward_ι_mk (H : LieIdeal R L) (x : L) :
    quotientBackward H (ι R (lieQuotientMap H x)) =
      Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x) := by
  rw [quotientBackward, lift_ι_apply, quotientGenerator_mk]

theorem quotientForward_comp_backward (H : LieIdeal R L) :
    (quotientForward H).comp (quotientBackward H) = AlgHom.id R _ := by
  apply hom_ext_ι
  intro z
  obtain ⟨x, rfl⟩ := lieQuotientMap_surjective H z
  change quotientForward H (quotientBackward H (ι R (lieQuotientMap H x))) =
    ι R (lieQuotientMap H x)
  rw [quotientBackward_ι_mk, quotientForward_mk, quotientMap_ι]

theorem quotientBackward_comp_forward (H : LieIdeal R L) :
    (quotientBackward H).comp (quotientForward H) = AlgHom.id R _ := by
  apply Ideal.Quotient.algHom_ext
  apply hom_ext_ι
  intro x
  change quotientBackward H
    (quotientForward H (Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x))) =
      Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x)
  rw [quotientForward_mk, quotientMap_ι, quotientBackward_ι_mk]

/-- Enveloping algebras preserve quotients by Lie ideals, with the generated two-sided ideal. -/
def quotientEquiv (H : LieIdeal R L) :
    (UniversalEnvelopingAlgebra R L ⧸ (lieIdealGenerated H).asIdeal) ≃ₐ[R]
      UniversalEnvelopingAlgebra R (L ⧸ H) :=
  AlgEquiv.ofAlgHom (quotientForward H) (quotientBackward H)
    (quotientForward_comp_backward H) (quotientBackward_comp_forward H)

@[simp] theorem quotientEquiv_mk (H : LieIdeal R L) (x : UniversalEnvelopingAlgebra R L) :
    quotientEquiv H (Ideal.Quotient.mk (lieIdealGenerated H).asIdeal x) = quotientMap H x := rfl

@[simp] theorem quotientEquiv_mk_ι (H : LieIdeal R L) (x : L) :
    quotientEquiv H (Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x)) =
      ι R (lieQuotientMap H x) := quotientMap_ι H x

@[simp] theorem quotientEquiv_symm_ι_mk (H : LieIdeal R L) (x : L) :
    (quotientEquiv H).symm (ι R (lieQuotientMap H x)) =
      Ideal.Quotient.mk (lieIdealGenerated H).asIdeal (ι R x) :=
  quotientBackward_ι_mk H x

theorem quotientMap_eq_zero_iff (H : LieIdeal R L) (x : UniversalEnvelopingAlgebra R L) :
    quotientMap H x = 0 ↔ x ∈ lieIdealGenerated H := by
  rw [← quotientEquiv_mk H x, ← map_zero (quotientEquiv H),
    (quotientEquiv H).injective.eq_iff, Ideal.Quotient.eq_zero_iff_mem]
  rfl

/-- Exact equality of the kernel as a two-sided ideal. -/
theorem ker_quotientMap (H : LieIdeal R L) :
    TwoSidedIdeal.ker (quotientMap H) = lieIdealGenerated H := by
  ext x
  rw [TwoSidedIdeal.mem_ker, quotientMap_eq_zero_iff]

/-- The same kernel equality in the native left-ideal API. -/
theorem ringKer_quotientMap (H : LieIdeal R L) :
    RingHom.ker (quotientMap H).toRingHom = (lieIdealGenerated H).asIdeal := by
  ext x
  exact quotientMap_eq_zero_iff H x

/-- The same kernel equality as a submodule over the coefficient ring. -/
theorem linearKer_quotientMap (H : LieIdeal R L) :
    LinearMap.ker (quotientMap H).toLinearMap = (lieIdealGenerated H).asIdeal.restrictScalars R := by
  ext x
  exact quotientMap_eq_zero_iff H x

end EnvelopingIsomorphism.Enveloping
