import Mathlib.Order.Partition.Finpartition
import Mathlib.Order.SuccPred.Tree

/-! A finite hierarchy actually generated by successive native finite partitions.
The recursive construction stops at singleton labels and strictly decreases the
cardinality at every edge. The native RootedTree adapter is supplied below. -/

noncomputable section

namespace EnvelopingIsomorphism.Deformation.Kontsevich.ClusterPartitionTree

open scoped Classical

variable {I : Type*} [DecidableEq I]

/-- The prescribed partition is used only at nontrivial clusters. -/
def children (P : ∀ A : Finset I, Finpartition A) (A : Finset I) : Finset (Finset I) :=
  if 1 < A.card then (P A).parts else ∅

@[simp] theorem mem_children (P : ∀ A : Finset I, Finpartition A) (A B : Finset I) :
    B ∈ children P A ↔ 1 < A.card ∧ B ∈ (P A).parts := by
  by_cases h : 1 < A.card <;> simp [children, h]

theorem child_subset (P : ∀ A : Finset I, Finpartition A) {A B : Finset I}
    (h : B ∈ children P A) : B ⊆ A := (P A).subset ((mem_children P A B).mp h).2

theorem child_nonempty (P : ∀ A : Finset I, Finpartition A) {A B : Finset I}
    (h : B ∈ children P A) : B.Nonempty :=
  (P A).nonempty_of_mem_parts ((mem_children P A B).mp h).2

variable (P : ∀ A : Finset I, Finpartition A)
variable (hproper : ∀ A, 1 < A.card → ∀ B ∈ (P A).parts, B.card < A.card)

include hproper

theorem child_card_lt {A B : Finset I} (h : B ∈ children P A) : B.card < A.card :=
  hproper A ((mem_children P A B).mp h).1 B ((mem_children P A B).mp h).2

theorem child_ssubset {A B : Finset I} (h : B ∈ children P A) : B ⊂ A := by
  apply Finset.ssubset_iff_subset_ne.mpr
  refine ⟨child_subset P h, ?_⟩
  intro he
  have hc := child_card_lt P hproper h
  exact (ne_of_lt hc) (congrArg Finset.card he)

/-- The actual finite set of reachable cluster labels, built by well-founded recursion. -/
def clusters (hproper : ∀ A, 1 < A.card → ∀ B ∈ (P A).parts, B.card < A.card)
    (A : Finset I) : Finset (Finset I) :=
  insert A ((children P A).attach.biUnion (fun B ↦ clusters hproper B.val))
termination_by A.card
decreasing_by exact child_card_lt P hproper B.property

theorem mem_clusters (A B : Finset I) :
    B ∈ clusters P hproper A ↔ B = A ∨ ∃ C ∈ children P A, B ∈ clusters P hproper C := by
  rw [clusters]
  simp

@[simp] theorem root_mem_clusters (A : Finset I) : A ∈ clusters P hproper A :=
  (mem_clusters P hproper A A).mpr (Or.inl rfl)

theorem child_mem_clusters {A B : Finset I} (h : B ∈ children P A) :
    B ∈ clusters P hproper A :=
  (mem_clusters P hproper A B).mpr (Or.inr ⟨B, h, root_mem_clusters P hproper B⟩)

theorem clusters_child_subset {A B : Finset I} (h : B ∈ children P A) :
    clusters P hproper B ⊆ clusters P hproper A := by
  intro C hC
  exact (mem_clusters P hproper A C).mpr (Or.inr ⟨B, h, hC⟩)

/-- Every generated label lies inside the initial cluster. -/
theorem subset_of_mem_clusters (A B : Finset I) (hB : B ∈ clusters P hproper A) : B ⊆ A := by
  induction A using Finset.strongInductionOn generalizing B
  rename_i A ih
  rcases (mem_clusters P hproper A B).mp hB with rfl | ⟨C, hC, hBC⟩
  · exact Finset.Subset.refl _
  · exact (ih C (child_ssubset P hproper hC) B hBC).trans (child_subset P hC)

/-- Nonempty roots produce only nonempty cluster labels. -/
theorem nonempty_of_mem_clusters (A B : Finset I) (hA : A.Nonempty)
    (hB : B ∈ clusters P hproper A) : B.Nonempty := by
  induction A using Finset.strongInductionOn generalizing B
  rename_i A ih
  rcases (mem_clusters P hproper A B).mp hB with rfl | ⟨C, hC, hBC⟩
  · exact hA
  · exact ih C (child_ssubset P hproper hC) B (child_nonempty P hC) hBC

/-- Every generated cluster brings along its entire recursively generated subtree. -/
theorem clusters_subset_of_mem (A B : Finset I) (hB : B ∈ clusters P hproper A) :
    clusters P hproper B ⊆ clusters P hproper A := by
  induction A using Finset.strongInductionOn generalizing B
  rename_i A ih
  rcases (mem_clusters P hproper A B).mp hB with rfl | ⟨C, hC, hBC⟩
  · exact Finset.Subset.refl _
  · exact (ih C (child_ssubset P hproper hC) B hBC).trans (clusters_child_subset P hproper hC)

/-- Every original point occurs as an actual singleton leaf label. -/
theorem singleton_mem_clusters (A : Finset I) (i : I) (hi : i ∈ A) :
    {i} ∈ clusters P hproper A := by
  induction A using Finset.strongInductionOn
  rename_i A ih
  by_cases hA : 1 < A.card
  · obtain ⟨B, hB, hiB⟩ := (P A).exists_mem hi
    have hc : B ∈ children P A := (mem_children P A B).mpr ⟨hA, hB⟩
    exact clusters_child_subset P hproper hc (ih B (child_ssubset P hproper hc) hiB)
  · have he : A = {i} := Finset.eq_singleton_iff_unique_mem.mpr
      ⟨hi, fun j hj ↦ Finset.card_le_one.mp (Nat.le_of_not_gt hA) j hj i hi⟩
    rw [he]
    exact root_mem_clusters P hproper {i}

/-- The recursively generated family is laminar, by disjointness of the actual partitions. -/
theorem laminar (A B C : Finset I) (hB : B ∈ clusters P hproper A)
    (hC : C ∈ clusters P hproper A) : B ⊆ C ∨ C ⊆ B ∨ Disjoint B C := by
  induction A using Finset.strongInductionOn generalizing B C
  rename_i A ih
  rcases (mem_clusters P hproper A B).mp hB with rfl | ⟨D, hD, hBD⟩
  · exact Or.inr (Or.inl (subset_of_mem_clusters P hproper _ C hC))
  rcases (mem_clusters P hproper A C).mp hC with rfl | ⟨E, hE, hCE⟩
  · exact Or.inl ((subset_of_mem_clusters P hproper D B hBD).trans (child_subset P hD))
  by_cases hDE : D = E
  · subst E
    exact ih D (child_ssubset P hproper hD) B C hBD hCE
  · exact Or.inr (Or.inr (((P A).disjoint ((mem_children P A D).mp hD).2
      ((mem_children P A E).mp hE).2 hDE).mono
        (subset_of_mem_clusters P hproper D B hBD)
        (subset_of_mem_clusters P hproper E C hCE)))

/-- Reachable labels nested inside a reachable cluster are generated by that cluster. -/
theorem mem_clusters_of_subset (A B C : Finset I) (hA : A.Nonempty)
    (hB : B ∈ clusters P hproper A) (hC : C ∈ clusters P hproper A) (hBC : B ⊆ C) :
    B ∈ clusters P hproper C := by
  induction A using Finset.strongInductionOn generalizing B C
  rename_i A ih
  rcases (mem_clusters P hproper A C).mp hC with rfl | ⟨D, hD, hCD⟩
  · exact hB
  have hCDsub := subset_of_mem_clusters P hproper D C hCD
  rcases (mem_clusters P hproper A B).mp hB with rfl | ⟨E, hE, hBE⟩
  · have hh := Finset.card_le_card (hBC.trans hCDsub)
    have hl := child_card_lt P hproper hD
    omega
  have hBnon : B.Nonempty := nonempty_of_mem_clusters P hproper E B (child_nonempty P hE) hBE
  have hDE : D = E := by
    obtain ⟨i, hi⟩ := hBnon
    exact (P A).eq_of_mem_parts ((mem_children P A D).mp hD).2
      ((mem_children P A E).mp hE).2 (hCDsub (hBC hi))
        (subset_of_mem_clusters P hproper E B hBE hi)
  subst E
  exact ih D (child_ssubset P hproper hD) B C (child_nonempty P hD) hBE hCD hBC

/-- The tree's descendant relation is exactly inclusion among actual reachable labels. -/
theorem descendants_iff_subset (A C : Finset I) (hA : A.Nonempty)
    (hC : C ∈ clusters P hproper A) (B : Finset I) :
    B ∈ clusters P hproper C ↔ B ∈ clusters P hproper A ∧ B ⊆ C := by
  constructor
  · intro hB
    exact ⟨clusters_subset_of_mem P hproper A C hC hB, subset_of_mem_clusters P hproper C B hB⟩
  · rintro ⟨hB, hBC⟩
    exact mem_clusters_of_subset P hproper A B C hA hB hC hBC

/-- Every nontrivial cluster has at least two actual children. -/
theorem one_lt_card_children (A : Finset I) (hA : 1 < A.card) : 1 < (children P A).card := by
  rw [children, if_pos hA]
  by_contra h
  have hc : (P A).parts.card ≤ 1 := Nat.le_of_not_gt h
  obtain ⟨i, hi⟩ := Finset.card_pos.mp (by omega : 0 < A.card)
  obtain ⟨B, hB, _⟩ := (P A).exists_mem hi
  have he : (P A).parts = {B} := Finset.eq_singleton_iff_unique_mem.mpr
    ⟨hB, fun C hC ↦ Finset.card_le_one.mp hc C hC B hB⟩
  have hBA : B = A := by simpa only [he, Finset.sup_singleton, id_eq] using (P A).sup_parts
  have hh := hproper A hA B hB
  rw [hBA] at hh
  exact lt_irrefl _ hh

/-- Among nonempty labels the recursion stops exactly at singletons. -/
theorem children_empty_iff (A : Finset I) (hA : A.Nonempty) :
    children P A = ∅ ↔ A.card = 1 := by
  constructor
  · intro h
    have hc : ¬1 < A.card := by
      intro hc
      have hh := one_lt_card_children P hproper A hc
      rw [h, Finset.card_empty] at hh
      omega
    have hp := Finset.card_pos.mpr hA
    omega
  · intro h
    simp [children, h]

/-- A prescribed partition edge is exactly an immediate inclusion among the
actually reachable labels. No predecessor relation is assumed. -/
theorem child_iff_immediate (R A B : Finset I) (hR : R.Nonempty)
    (hA : A ∈ clusters P hproper R) (hB : B ∈ clusters P hproper R) :
    B ∈ children P A ↔ B ⊂ A ∧
      ¬∃ C ∈ clusters P hproper R, C ⊂ A ∧ B ⊂ C := by
  constructor
  · intro h
    refine ⟨child_ssubset P hproper h, ?_⟩
    rintro ⟨C, hC, hCA, hBC⟩
    have hCin := mem_clusters_of_subset P hproper R C A hR hC hA
      (Finset.ssubset_iff_subset_ne.mp hCA).1
    rcases (mem_clusters P hproper A C).mp hCin with he | ⟨D, hD, hCD⟩
    · exact (Finset.ssubset_iff_subset_ne.mp hCA).2 he
    have hCDsub := subset_of_mem_clusters P hproper D C hCD
    obtain ⟨i, hi⟩ := child_nonempty P h
    have hBD : B = D := (P A).eq_of_mem_parts ((mem_children P A B).mp h).2
      ((mem_children P A D).mp hD).2 hi (hCDsub ((Finset.ssubset_iff_subset_ne.mp hBC).1 hi))
    have hCB : C ⊆ B := hBD ▸ hCDsub
    exact (Finset.ssubset_iff_subset_ne.mp hBC).2
      (Finset.Subset.antisymm (Finset.ssubset_iff_subset_ne.mp hBC).1 hCB)
  · rintro ⟨hBA, hno⟩
    have hBin := mem_clusters_of_subset P hproper R B A hR hB hA
      (Finset.ssubset_iff_subset_ne.mp hBA).1
    rcases (mem_clusters P hproper A B).mp hBin with he | ⟨D, hD, hBD⟩
    · exact ((Finset.ssubset_iff_subset_ne.mp hBA).2 he).elim
    have he : B = D := by
      by_contra he
      apply hno
      refine ⟨D, ?_, child_ssubset P hproper hD, ?_⟩
      · exact clusters_subset_of_mem P hproper R A hA (child_mem_clusters P hproper hD)
      · exact Finset.ssubset_iff_subset_ne.mpr ⟨subset_of_mem_clusters P hproper D B hBD, he⟩
    exact he ▸ hD

end EnvelopingIsomorphism.Deformation.Kontsevich.ClusterPartitionTree
