import EnvelopingIsomorphism.Deformation.Kontsevich.AnchorChangeJacobian
import EnvelopingIsomorphism.Deformation.Kontsevich.GeometricWeights
import EnvelopingIsomorphism.Deformation.Kontsevich.OrientedFormChangeVariables
import EnvelopingIsomorphism.Deformation.Kontsevich.FixedAnchorPermutation
import EnvelopingIsomorphism.Deformation.Kontsevich.BlockPermutationSign
import EnvelopingIsomorphism.Deformation.GeneralGraphMixedProfiles

/-!
# Internal relabelling of actual geometric graph integrals

Anchor exchanges use the actual normalization homeomorphism, full harmonic
form covariance, and its positive Jacobian. The change-of-variables identity
does not assume global integrability; integrability equivalence is also proved.
-/

noncomputable section

namespace EnvelopingIsomorphism.Deformation.Kontsevich.GeometricWeights

open GraphForms Set MeasureTheory
open scoped Topology

variable {n m : ℕ}

/-- Push forward every internal endpoint of a raw edge; external labels stay fixed. -/
def relabelEdge (σ : Equiv.Perm (Fin (n + 1))) (e : Edge n m) : Edge n m where
  source := σ e.source
  target := Sum.map σ id e.target

@[simp] theorem relabelEdge_one (e : Edge n m) : relabelEdge 1 e = e := by
  cases e with
  | mk source target => cases target <;> rfl

@[simp] theorem relabelEdge_mul (σ τ : Equiv.Perm (Fin (n + 1))) (e : Edge n m) :
    relabelEdge (σ * τ) e = relabelEdge σ (relabelEdge τ e) := by
  cases e with
  | mk source target => cases target <;> rfl

@[simp] theorem relabelEdge_anchorSwap (j : Fin (n + 1)) (e : Edge n m) :
    relabelEdge (Equiv.swap 0 j) e = anchorSwapEdge j e := rfl

/-- Every internal permutation is generated by exchanges with the normalized
anchor. This transports already proved geometric invariance, without replacing
it by an outgoing-edge-order argument. -/
theorem relabel_invariance_of_anchorSwaps {r : ℕ} {B : Sort*}
    (F : (Fin r → Edge n m) → B)
    (hF : ∀ j edges, F (fun a => anchorSwapEdge j (edges a)) = F edges)
    (σ : Equiv.Perm (Fin (n + 1))) (edges : Fin r → Edge n m) :
    F (fun a => relabelEdge σ (edges a)) = F edges := by
  have hswap (i j : Fin (n + 1)) (hij : i ≠ j) (es : Fin r → Edge n m) :
      F (fun a => relabelEdge (Equiv.swap i j) (es a)) = F es := by
    by_cases hj : j = 0
    · subst j
      rw [Equiv.swap_comm i 0]
      exact hF i es
    · have heq : Equiv.swap i j = Equiv.swap 0 i * Equiv.swap 0 j * Equiv.swap 0 i := by
        have h := Equiv.swap_mul_swap_mul_swap (x := j) (y := (0 : Fin (n + 1))) (z := i) hj hij.symm
        rw [Equiv.swap_comm j 0] at h
        exact h.symm
      rw [heq]
      simp only [relabelEdge_mul, relabelEdge_anchorSwap]
      rw [hF, hF, hF]
  induction σ using Equiv.Perm.swap_induction_on with
  | one => simp only [relabelEdge_one]
  | swap_mul σ i j hij ih =>
      simp only [relabelEdge_mul]
      rw [hswap i j hij]
      exact ih

theorem anchorChangeReal_mem_domain (j : Fin (n + 1))
    {x : Fin (dimension n m) → ℝ} (hx : x ∈ realDomain n m) :
    anchorChangeReal j x ∈ realDomain n m := by
  change Admissible ((realCoordinates n m).symm
    (realCoordinates n m (anchorChangeRaw j ((realCoordinates n m).symm x))))
  rw [LinearEquiv.symm_apply_apply]
  exact anchorChangeRaw_admissible j hx

theorem anchorChangeReal_involutive_on_domain (j : Fin (n + 1))
    {x : Fin (dimension n m) → ℝ} (hx : x ∈ realDomain n m) :
    anchorChangeReal j (anchorChangeReal j x) = x := by
  simp only [anchorChangeReal, LinearEquiv.symm_apply_apply,
    anchorChangeRaw_involutive j hx, LinearEquiv.apply_symm_apply]

theorem anchorChangeReal_image_domain (j : Fin (n + 1)) :
    anchorChangeReal (m := m) j '' realDomain n m = realDomain n m := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact anchorChangeReal_mem_domain j hy
  · intro hx
    exact ⟨anchorChangeReal j x, anchorChangeReal_mem_domain j hx,
      anchorChangeReal_involutive_on_domain j hx⟩

theorem anchorChangeReal_injOn (j : Fin (n + 1)) :
    Set.InjOn (anchorChangeReal (m := m) j) (realDomain n m) := by
  intro x hx y hy hxy
  have h := congrArg (anchorChangeReal j) hxy
  simpa only [anchorChangeReal_involutive_on_domain j hx,
    anchorChangeReal_involutive_on_domain j hy] using h

theorem contDiffAt_anchorChangeReal (j : Fin (n + 1))
    {x : Fin (dimension n m) → ℝ} (hx : x ∈ realDomain n m) :
    ContDiffAt ℝ ⊤ (anchorChangeReal j) x := by
  let R := realCoordinatesContinuous n m
  have hraw := contDiffAt_anchorChangeRaw j ((realCoordinates n m).symm x)
    (ne_of_gt (hx.interiorPoint_im_pos j))
  change ContDiffAt ℝ ⊤ (fun y => R (anchorChangeRaw j (R.symm y))) x
  exact R.contDiff.contDiffAt.comp x (hraw.comp x R.symm.contDiff.contDiffAt)

/-- The actual real-coordinate normalization is a genuine open coordinate equivalence. -/
def anchorChangeRealHomeomorph (j : Fin (n + 1)) :
    OpenPartialHomeomorph (Fin (dimension n m) → ℝ) (Fin (dimension n m) → ℝ) where
  toFun := anchorChangeReal j
  invFun := anchorChangeReal j
  source := realDomain n m
  target := realDomain n m
  map_source' := fun _ hx => anchorChangeReal_mem_domain j hx
  map_target' := fun _ hx => anchorChangeReal_mem_domain j hx
  left_inv' := fun _ hx => anchorChangeReal_involutive_on_domain j hx
  right_inv' := fun _ hx => anchorChangeReal_involutive_on_domain j hx
  open_source := isOpen_realDomain n m
  open_target := isOpen_realDomain n m
  continuousOn_toFun := fun _ hx => (contDiffAt_anchorChangeReal j hx).continuousAt.continuousWithinAt
  continuousOn_invFun := fun _ hx => (contDiffAt_anchorChangeReal j hx).continuousAt.continuousWithinAt

theorem anchorChangeReal_jacobian_pos (j : Fin (n + 1))
    {x : Fin (dimension n m) → ℝ} (hx : x ∈ realDomain n m) :
    0 < (fderiv ℝ (anchorChangeReal j) x).det := by
  have h := det_fderiv_anchorChangeReal_pos j hx
  simpa only [LinearEquiv.apply_symm_apply] using h

/-- Density covariance includes the true derivative of the variable affine
normalizer and the oriented positive Jacobian. -/
theorem realDensity_anchorChangeReal (j : Fin (n + 1))
    (edges : Fin (dimension n m) → Edge n m)
    {x : Fin (dimension n m) → ℝ} (hx : x ∈ realDomain n m) :
    realDensity (fun a => anchorSwapEdge j (edges a)) x =
      |(fderiv ℝ (anchorChangeReal j) x).det| • realDensity edges (anchorChangeReal j x) := by
  rw [abs_of_pos (anchorChangeReal_jacobian_pos j hx), smul_eq_mul]
  have hdet := det_fderiv_anchorChangeReal_eq j hx
  simp only [LinearEquiv.apply_symm_apply] at hdet
  change (fderiv ℝ (anchorChangeReal j) x).det =
    (fderiv ℝ (anchorChangeRaw j) ((realCoordinates n m).symm x)).det at hdet
  change topDensity (fun a => anchorSwapEdge j (edges a)) ((realCoordinates n m).symm x) =
    (fderiv ℝ (anchorChangeReal j) x).det *
      topDensity edges ((realCoordinates n m).symm
        (realCoordinates n m (anchorChangeRaw j ((realCoordinates n m).symm x))))
  rw [LinearEquiv.symm_apply_apply, hdet]
  exact topDensity_anchorChangeRaw_det j edges hx

/-- Genuine anchor-change symmetry of the actual raw integral, keeping the
corresponding edge order. No global L1 hypothesis is silently added. -/
theorem rawIntegral_anchorSwap (j : Fin (n + 1))
    (edges : Fin (dimension n m) → Edge n m) :
    rawIntegral (fun a => anchorSwapEdge j (edges a)) = rawIntegral edges := by
  have h := integral_image_eq_integral_abs_det_fderiv_smul volume (measurableSet_realDomain n m)
    (fun x hx => ((contDiffAt_anchorChangeReal j hx).differentiableAt (by simp)).hasFDerivAt.hasFDerivWithinAt)
    (anchorChangeReal_injOn j) (realDensity edges)
  rw [anchorChangeReal_image_domain] at h
  unfold rawIntegral
  rw [h]
  apply setIntegral_congr_fun (measurableSet_realDomain n m)
  intro x hx
  exact realDensity_anchorChangeReal j edges hx

theorem absolutelyIntegrable_anchorSwap_iff (j : Fin (n + 1))
    (edges : Fin (dimension n m) → Edge n m) :
    AbsolutelyIntegrable (fun a => anchorSwapEdge j (edges a)) ↔ AbsolutelyIntegrable edges := by
  have h := integrableOn_image_iff_integrableOn_abs_det_fderiv_smul volume (measurableSet_realDomain n m)
    (fun x hx => ((contDiffAt_anchorChangeReal j hx).differentiableAt (by simp)).hasFDerivAt.hasFDerivWithinAt)
    (anchorChangeReal_injOn j) (realDensity edges)
  rw [anchorChangeReal_image_domain] at h
  exact (h.trans (integrableOn_congr_fun
    (fun x hx => (realDensity_anchorChangeReal j edges hx).symm) (measurableSet_realDomain n m))).symm

/-- All internal relabellings preserve the actual raw integral when the
corresponding edge list keeps its order. -/
theorem rawIntegral_relabel (σ : Equiv.Perm (Fin (n + 1)))
    (edges : Fin (dimension n m) → Edge n m) :
    rawIntegral (fun a => relabelEdge σ (edges a)) = rawIntegral edges :=
  relabel_invariance_of_anchorSwaps rawIntegral rawIntegral_anchorSwap σ edges

/-- Fixed-anchor permutations agree with the native even-complex-block
coordinate maps whose determinant is proved to be one. -/
theorem rawIntegral_fixedAnchor (σ : Equiv.Perm (Fin n))
    (edges : Fin (dimension n m) → Edge n m) :
    rawIntegral (fun a => relabelEdge (extendFixedAnchor σ) (edges a)) = rawIntegral edges :=
  rawIntegral_relabel (extendFixedAnchor σ) edges

theorem absolutelyIntegrable_relabel_iff (σ : Equiv.Perm (Fin (n + 1)))
    (edges : Fin (dimension n m) → Edge n m) :
    AbsolutelyIntegrable (fun a => relabelEdge σ (edges a)) ↔ AbsolutelyIntegrable edges :=
  iff_of_eq (relabel_invariance_of_anchorSwaps AbsolutelyIntegrable
    (fun j es => propext (absolutelyIntegrable_anchorSwap_iff j es)) σ edges)

/-- Combining vertex relabelling with an independent edge-order permutation
keeps exactly the latter's determinant sign. -/
theorem rawIntegral_relabel_permute (σ : Equiv.Perm (Fin (n + 1)))
    (τ : Equiv.Perm (Fin (dimension n m))) (edges : Fin (dimension n m) → Edge n m) :
    rawIntegral (fun a => relabelEdge σ (edges (τ a))) =
      (Equiv.Perm.sign τ : ℝ) * rawIntegral edges := by
  rw [rawIntegral_relabel, rawIntegral_permute]

/-- Internal relabelling also preserves the actual outgoing-factorial normalization. -/
theorem outgoingFactor_relabel (q : Fin (n + 1) → ℕ) (σ : Equiv.Perm (Fin (n + 1))) :
    outgoingFactor (fun v => q (σ.symm v)) = outgoingFactor q := by
  unfold outgoingFactor
  exact Equiv.prod_comp σ.symm (fun v => ((q v).factorial : ℝ)⁻¹)

/-- A combinatorially transported ordered edge list has the same actual
normalized geometric integral. The hypothesis concerns endpoints/order only. -/
theorem geometricWeight_eq_of_orderedEdges_relabel {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m)
    (σ : Equiv.Perm (Fin (n + 1)))
    (Γ' : KontsevichGraph.General.Graph (fun v => q (σ.symm v)) m)
    (order : Fin (dimension n m) ≃ KontsevichGraph.General.Edge q)
    (order' : Fin (dimension n m) ≃ KontsevichGraph.General.Edge (fun v => q (σ.symm v)))
    (horder : orderedEdges Γ' order' = fun a => relabelEdge σ (orderedEdges Γ order a)) :
    geometricWeight Γ' order' = geometricWeight Γ order := by
  simp only [geometricWeight, horder, rawIntegral_relabel, outgoingFactor_relabel]

theorem geometricWeight_eq_of_orderedEdges_relabel_permute {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m)
    (σ : Equiv.Perm (Fin (n + 1)))
    (Γ' : KontsevichGraph.General.Graph (fun v => q (σ.symm v)) m)
    (order : Fin (dimension n m) ≃ KontsevichGraph.General.Edge q)
    (order' : Fin (dimension n m) ≃ KontsevichGraph.General.Edge (fun v => q (σ.symm v)))
    (τ : Equiv.Perm (Fin (dimension n m)))
    (horder : orderedEdges Γ' order' = fun a => relabelEdge σ (orderedEdges Γ order (τ a))) :
    geometricWeight Γ' order' = (Equiv.Perm.sign τ : ℝ) * geometricWeight Γ order := by
  simp only [geometricWeight, horder, rawIntegral_relabel_permute, outgoingFactor_relabel]
  ring

open KontsevichGraph.General
open scoped BigOperators Classical

/-- Corresponding dependent edge orders transport actual geometric endpoints. -/
theorem orderedEdges_permuteProfile {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (σ : Equiv.Perm (Fin (n + 1)))
    (order : Fin (dimension n m) ≃ KontsevichGraph.General.Edge q) :
    orderedEdges (Γ.permuteProfile σ) (order.trans (profileEdgeEquiv q σ)) =
      fun a => relabelEdge σ (orderedEdges Γ order a) := by
  funext a
  change (⟨_, _⟩ : GraphForms.Edge n m) = ⟨_, _⟩
  congr 1
  exact Γ.permuteProfile_target σ (order a)

/-- Actual weight covariance with its transported dependent edge order. -/
theorem geometricWeight_permuteProfile {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (σ : Equiv.Perm (Fin (n + 1)))
    (order : Fin (dimension n m) ≃ KontsevichGraph.General.Edge q) :
    geometricWeight (Γ.permuteProfile σ) (order.trans (profileEdgeEquiv q σ)) =
      geometricWeight Γ order :=
  geometricWeight_eq_of_orderedEdges_relabel Γ σ (Γ.permuteProfile σ) order
    (order.trans (profileEdgeEquiv q σ)) (orderedEdges_permuteProfile Γ σ order)

/-- The exact new-to-old row permutation between the two canonical orders. -/
def canonicalProfileRows {q : Fin (n + 1) → ℕ}
    (hq : ∑ v, q v = dimension n m) (σ : Equiv.Perm (Fin (n + 1))) :
    Equiv.Perm (Fin (dimension n m)) :=
  (finCongr hq).permCongr (profileRowPerm q σ).symm

theorem canonicalProfileRows_sign {q : Fin (n + 1) → ℕ}
    (hq : ∑ v, q v = dimension n m) (σ : Equiv.Perm (Fin (n + 1))) :
    (canonicalProfileRows hq σ).sign = (profileRowPerm q σ).sign := by
  simp [canonicalProfileRows]

theorem canonicalOrder_permuteProfile {q : Fin (n + 1) → ℕ}
    (hq : ∑ v, q v = dimension n m) (σ : Equiv.Perm (Fin (n + 1))) :
    canonicalOrder ((profileArity_sum q σ).trans hq) =
      (canonicalProfileRows hq σ).trans
        ((canonicalOrder hq).trans (profileEdgeEquiv q σ)) := by
  apply Equiv.ext
  intro a
  simp [canonicalOrder, canonicalProfileRows, profileRowPerm, Equiv.permCongr]

/-- Canonical mixed-arity geometric weights carry precisely the true block sign. -/
theorem canonicalWeight_permuteProfile_sign {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) :
    canonicalWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      ((profileRowPerm q σ).sign : ℝ) * canonicalWeight Γ hq := by
  unfold canonicalWeight
  rw [canonicalOrder_permuteProfile, geometricWeight_permute,
    geometricWeight_permuteProfile, canonicalProfileRows_sign]

/-- Pairwise even block-length products remove the canonical edge-order sign. -/
theorem canonicalWeight_permuteProfile_of_even_products {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) (heven : ∀ v w, v ≠ w → Even (q v * q w)) :
    canonicalWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      canonicalWeight Γ hq := by
  rw [canonicalWeight_permuteProfile_sign Γ hq σ,
    profileRowPerm_sign_eq_one_of_even_products q σ heven]
  simp

/-- At most one odd outgoing block is enough for invariance under all internal permutations. -/
theorem canonicalWeight_permuteProfile_of_at_most_one_odd {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) (heven : ∀ v w, v ≠ w → Even (q v) ∨ Even (q w)) :
    canonicalWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      canonicalWeight Γ hq := by
  rw [canonicalWeight_permuteProfile_sign Γ hq σ,
    profileRowPerm_sign_eq_one_of_at_most_one_odd q σ heven]
  simp

/-- All-even arities, including the binary profile, have invariant canonical weights. -/
theorem canonicalWeight_permuteProfile_of_even {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) (heven : ∀ v, Even (q v)) :
    canonicalWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      canonicalWeight Γ hq := by
  rw [canonicalWeight_permuteProfile_sign Γ hq σ, profileRowPerm_sign_eq_one_of_even q σ heven]
  simp

/-- A single exceptional arity may move to any vertex without changing the actual weight. -/
theorem canonicalWeight_permuteProfile_of_even_off {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) (i : Fin (n + 1))
    (heven : ∀ v, v ≠ i → Even (q v)) :
    canonicalWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      canonicalWeight Γ hq := by
  rw [canonicalWeight_permuteProfile_sign Γ hq σ, profileRowPerm_sign_eq_one_of_even_off q σ i heven]
  simp

/-- This covers a vector (a=1) or curvature (a=3) vertex among bivectors. -/
theorem canonicalWeight_permuteProfile_oneExceptional (a : ℕ) (i : Fin (n + 1))
    (Γ : KontsevichGraph.General.Graph (oneExceptionalArity a i) m)
    (hq : ∑ v, oneExceptionalArity a i v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) :
    canonicalWeight (Γ.permuteProfile σ)
        ((profileArity_sum (oneExceptionalArity a i) σ).trans hq) = canonicalWeight Γ hq := by
  apply canonicalWeight_permuteProfile_of_even_off Γ hq σ i
  intro v hv
  simp [oneExceptionalArity_other a i v hv]

/-- Canonical binary geometric weights are invariant under every internal permutation. -/
theorem canonicalWeight_permuteProfile_binary
    (Γ : KontsevichGraph.General.Graph (fun _ : Fin (n + 1) => 2) m)
    (hq : ∑ _ : Fin (n + 1), 2 = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) :
    canonicalWeight (Γ.permuteProfile σ)
        ((profileArity_sum (fun _ => 2) σ).trans hq) = canonicalWeight Γ hq :=
  canonicalWeight_permuteProfile_of_even Γ hq σ (fun _ => by decide)

/-- Edge-order changes preserve absolute convergence of the actual density. -/
theorem absolutelyIntegrable_permute_iff
    (edges : Fin (dimension n m) → GraphForms.Edge n m)
    (σ : Equiv.Perm (Fin (dimension n m))) :
    AbsolutelyIntegrable (fun a => edges (σ a)) ↔ AbsolutelyIntegrable edges := by
  have hp (es : Fin (dimension n m) → GraphForms.Edge n m)
      (τ : Equiv.Perm (Fin (dimension n m))) (h : AbsolutelyIntegrable es) :
      AbsolutelyIntegrable (fun a => es (τ a)) := by
    change IntegrableOn (realDensity (fun a => es (τ a))) (realDomain n m)
    have he : realDensity (fun a => es (τ a)) =
        fun x => (Equiv.Perm.sign τ : ℝ) * realDensity es x := by
      funext x
      exact realDensity_permute es τ x
    rw [he]
    exact h.const_mul _
  constructor
  · intro h
    simpa only [Equiv.apply_symm_apply] using hp _ σ.symm h
  · exact hp edges σ

/-- Canonical reordering and internal coordinate relabelling preserve L1, even with odd blocks. -/
theorem absolutelyIntegrable_canonical_permuteProfile_iff {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) :
    AbsolutelyIntegrable (orderedEdges (Γ.permuteProfile σ)
        (canonicalOrder ((profileArity_sum q σ).trans hq))) ↔
      AbsolutelyIntegrable (orderedEdges Γ (canonicalOrder hq)) := by
  rw [canonicalOrder_permuteProfile hq σ]
  change AbsolutelyIntegrable (fun a =>
      orderedEdges (Γ.permuteProfile σ)
        ((canonicalOrder hq).trans (profileEdgeEquiv q σ)) (canonicalProfileRows hq σ a)) ↔ _
  rw [absolutelyIntegrable_permute_iff]
  rw [orderedEdges_permuteProfile Γ σ (canonicalOrder hq)]
  exact absolutelyIntegrable_relabel_iff σ (orderedEdges Γ (canonicalOrder hq))

/-- The MC normalization has the same internal vertex count on both sides. -/
theorem canonicalEffectiveWeight_permuteProfile_of_even_off {q : Fin (n + 1) → ℕ}
    (Γ : KontsevichGraph.General.Graph q m) (hq : ∑ v, q v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) (i : Fin (n + 1))
    (heven : ∀ v, v ≠ i → Even (q v)) :
    canonicalEffectiveWeight (Γ.permuteProfile σ) ((profileArity_sum q σ).trans hq) =
      canonicalEffectiveWeight Γ hq := by
  unfold canonicalEffectiveWeight
  rw [canonicalWeight_permuteProfile_of_even_off Γ hq σ i heven]

/-- Effective mixed weights keep the exact W/(n+1)! convention at every placement. -/
theorem canonicalEffectiveWeight_permuteProfile_oneExceptional (a : ℕ) (i : Fin (n + 1))
    (Γ : KontsevichGraph.General.Graph (oneExceptionalArity a i) m)
    (hq : ∑ v, oneExceptionalArity a i v = dimension n m)
    (σ : Equiv.Perm (Fin (n + 1))) :
    canonicalEffectiveWeight (Γ.permuteProfile σ)
        ((profileArity_sum (oneExceptionalArity a i) σ).trans hq) =
      canonicalEffectiveWeight Γ hq := by
  unfold canonicalEffectiveWeight
  rw [canonicalWeight_permuteProfile_oneExceptional a i Γ hq σ]

/-- Equality transport of a profile leaves its canonical geometric weight unchanged. -/
theorem canonicalWeight_castProfile {q q' : Fin (n + 1) → ℕ} (h : q = q')
    (Γ : KontsevichGraph.General.Graph q m)
    (hq : ∑ v, q v = dimension n m) (hq' : ∑ v, q' v = dimension n m) :
    canonicalWeight (KontsevichGraph.General.Graph.castProfileEquiv h m Γ) hq' =
      canonicalWeight Γ hq := by
  subst q'
  rfl

/-- The actual bijection between exceptional placements preserves canonical weights. -/
theorem canonicalWeight_oneExceptionalGraphEquiv (a : ℕ) (i : Fin (n + 1))
    (σ : Equiv.Perm (Fin (n + 1)))
    (Γ : KontsevichGraph.General.Graph (oneExceptionalArity a i) m)
    (hq : ∑ v, oneExceptionalArity a i v = dimension n m)
    (hq' : ∑ v, oneExceptionalArity a (σ i) v = dimension n m) :
    canonicalWeight (KontsevichGraph.General.Graph.oneExceptionalGraphEquiv a i σ m Γ) hq' =
      canonicalWeight Γ hq := by
  change canonicalWeight
    (KontsevichGraph.General.Graph.castProfileEquiv (profileArity_oneExceptional a i σ) m
      (Γ.permuteProfile σ)) hq' = _
  rw [canonicalWeight_castProfile (profileArity_oneExceptional a i σ) (Γ.permuteProfile σ)
    ((profileArity_sum (oneExceptionalArity a i) σ).trans hq) hq']
  exact canonicalWeight_permuteProfile_oneExceptional a i Γ hq σ

/-- The genuine graph bijection also preserves the effective MC weight at each placement. -/
theorem canonicalEffectiveWeight_oneExceptionalGraphEquiv (a : ℕ) (i : Fin (n + 1))
    (σ : Equiv.Perm (Fin (n + 1)))
    (Γ : KontsevichGraph.General.Graph (oneExceptionalArity a i) m)
    (hq : ∑ v, oneExceptionalArity a i v = dimension n m)
    (hq' : ∑ v, oneExceptionalArity a (σ i) v = dimension n m) :
    canonicalEffectiveWeight
        (KontsevichGraph.General.Graph.oneExceptionalGraphEquiv a i σ m Γ) hq' =
      canonicalEffectiveWeight Γ hq := by
  unfold canonicalEffectiveWeight
  rw [canonicalWeight_oneExceptionalGraphEquiv a i σ Γ hq hq']

end EnvelopingIsomorphism.Deformation.Kontsevich.GeometricWeights
